### ISSUE TITLE
Resource Quota section in kubectl describe namespace has invalid indentation

### ISSUE THREAD

**Issue by dty1er** [kubernetes/kubectl#1005]
**What happened**:

`Resource Quotas` section in the output of `kubectl describe namespaces` has invalid indentation.
It has only 1 space at the head.

<img width="368" alt="スクリーンショット 2021-01-12 123708" src="https://user-images.githubusercontent.com/60682957/104266458-ff6b0080-54d2-11eb-96e6-f8fdeb12d4d2.png">

**What you expected to happen**:

2 spaces should be located.

**How to reproduce it (as minimally and precisely as possible)**:

Apply below 2 manifests in any kubernetes cluster.

namespace.yaml
```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: kubecolor
  labels:
    name: kubecolor
```

resource_quota.yaml
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
```

**Anything else we need to know?**:

The root cause is that it uses `LEVEL_0` indentation instead of `LEVEL_1`.
ref: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L529-L560
For me it looks like it will be fixed by just changing `LEVEL_0` to `LEVEL_1` then remove the leading space.
I want to work on the fix if it sounds OK. Please give some opinions @soltysh @eddiezane 

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

WSL2

- OS (e.g: `cat /etc/os-release`):

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
