### ISSUE TITLE
auth can-i provides potentially misleading output with impersonate

### ISSUE THREAD

**Issue by raesene** [kubernetes/kubectl#1035]
**What happened**:

Usually when using `kubectl auth can-i`, a response from the server of `Warning: the server doesn't have a resource type` indicates that a typo has occurred and that the query is invalid. 

When using auth can-i for an account able to impersonate users returns the following results :

```bash
kubectl auth can-i impersonate users
Warning: the server doesn't have a resource type 'users'
yes
```

However having a resource type of users for impersonate is a valid option as shown in its [documentation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation)

**What you expected to happen**:

As users are a valid resources type for the impersonate verb, the warning shouldn't appear.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster role which can impersonate users

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: impersonator
rules:
- apiGroups: [""]
  resources: ["users", "groups", "serviceaccounts"]
  verbs: ["impersonate"]
```

Create a service account

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: impersonator
```

Create a cluster role binding for the service account and cluster role

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: impersonator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: impersonator
subjects:
- kind: ServiceAccount
  name: impersonator
  namespace: default
```

use auth can-i as that service account

```bash
kubectl auth can-i --as system:serviceaccount:default:impersonator impersonate users
```

**Anything else we need to know?**:

**Environment**:

```bash
 kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
