### ISSUE TITLE
Wrong port number displayed when port forwarding

### ISSUE THREAD

**Issue by fowlay** [kubernetes/kubectl#1036]
**What happened**:
The following command,
kubectl port-forward -n XXX service/YYY 8377:830
sets up port forwarding successfully, but the following is displayed in the console window:
Forwarding from 127.0.0.1:8377 -> 8830
Forwarding from [::1]:8377 -> 8830

**What you expected to happen**:
This should have been displayed:
Forwarding from 127.0.0.1:8377 -> 830
Forwarding from [::1]:8377 -> 830

**How to reproduce it (as minimally and precisely as possible)**:
Set up port forwarding as shown above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-23T07:40:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
N/A
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by rikatz** [comment]
hello,

can you please post your service object here?

kubectl get svc -n XXX service/YYY -o yaml

thanks

**Comment by fowlay** [comment]
Hi Rikatz, the service object in this case is a company internal entity so the name would not be of any use. If it would be of any help I can maybe run commands to gather information about the service object.

**Comment by fowlay** [comment]
About the issue - I should add that the actual port forwarding works fine. In the example above, a TCP client can connect to localhost:8377, reaching the remote service at port 830. It is maybe just a matter of the messages displayed in the console window, where the remote port comes out wrong.

**Comment by rikatz** [comment]
yes sure, I don't want the service name, but the spec :D

I want to try to reproduce here, as when I tried the same the correct port was shown!

**Comment by rikatz** [comment]
@fowlay ping :) 

Can you please provide the service object, so I can try to reproduce here?

Thanks

**Comment by loozhengyuan** [comment]
@rikatz Here's a repro:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repro
  labels:
    app: repro
spec:
  selector:
    matchLabels:
      app: repro
  template:
    metadata:
      labels:
        app: repro
    spec:
      containers:
        - name: web
          image: nginx
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: repro
  labels:
    app: repro
spec:
  selector:
    app: repro
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
```

```console
$ kubectl port-forward service/repro 65432:8080
Forwarding from 127.0.0.1:65432 -> 80
Forwarding from [::1]:65432 -> 80
```

In this case, port `8080` is the `targetPort` of the `Service` and port `80` is the port of the container expected to be forwarded based on the `targetPort` field. I'm not sure if this is a bug per se since port `80` is indeed the expected port.

I think perhaps, we can explore another way to represent the port when running `kubectl port-forward` on `Service` resources?

```console
$ kubectl port-forward service/repro 65432:8080
Forwarding from 127.0.0.1:65432 -> 8080 -> 80
Forwarding from [::1]:65432 -> 8080 -> 80
```
