### ISSUE TITLE
kubectl set env not working for initcontainers

### ISSUE THREAD

**Issue by mdepa** [kubernetes/kubectl#1042]
**What happened**:
I'm currently implementing a CI/CD pipeline where I want to initialize a container using an initcontainer image, the initialization is driven by parameters I'd like to pass to the init container as environment variables.

When I execute the command **kubectl set env --all=true deployment/my-app --from=configmap/my-configmap** the command succeed with output: 

deployment.apps/my-app updated 

But the initContainer image is not updated and the env vars are not valued. 

I attempted to use command: 

**kubectl set env -c init-image deployment/my-app --from=configmap/my-configmap** where init-image is the name of my initcontainer image, but the command failed with output: 

warning: deployments/my-app does not have any containers matching "init-image"
  

**What you expected to happen**:
Using the --all=true option I expected to be able to set environment variables values for any initcontainer image part of the deployment.

**How to reproduce it (as minimally and precisely as possible)**:
I provide a minimal deployment with a pod complete of image and initcontainer and a configmap with the env var I'd like to set on both images. 

To reproduce the issue, apply the deployment: 

**kubectl apply -f my-app.yaml**

Check that the initcontainer logged "blue" as env value and that the container image is continuously logging "blue" as using the same env var. 

Perform the following command: 

**kubectl set env  deployment/my-app --all=true --from=configmap/env-value**

Once the image is running, inspecting the log I would expect to read 'red' both into the image and initcontainer logs, however, the initcontainer log is still reporting 'blue': the configmap/env-value was not applied to the initcontainer image. 

In the following the sample deployment: 

```
apiVersion: v1
kind: List
items:        
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: my-app
    name: my-app
  spec: 
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: my-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          deployment: my-app
      spec:
        containers:
        - env:
          - name: SAMPLE_VALUE
            value: blue
          image: alpine:latest
          name: my-app
          command:
          - /bin/sh
          - -c 
          - 'while true; do echo $SAMPLE_VALUE; sleep 5; done'
          resources: {}
        initContainers:
        - command:
          - /bin/sh
          - -c
          - echo $SAMPLE_VALUE
          image: busybox
          name: init-image
          env:
          - name: SAMPLE_VALUE
            value: blue          
          resources: {}     
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: my-app

    name: env-value
  data:
   SAMPLE_VALUE: red
```

**Anything else we need to know?**: none

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.3+2fbd7c7", GitCommit:"2fbd7c7", GitTreeState:"clean", BuildDate:"2020-10-15T16:25:45Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: on premises Openshift 4.7
- OS (e.g: `cat /etc/os-release`): Current client OS is Windows 10
