### ISSUE TITLE
error: SchemaError(xxx.crd.path.field): array should have exactly one sub-item

### ISSUE THREAD

**Issue by leviisfool** [kubernetes/kubectl#1045]
**How to reproduce it (as minimally and precisely as possible)**:

crd definition apply to k8s:
```yaml
endpoints:
  items:
    type: object
  type: array
  x-kubernetes-preserve-unknown-fields: true
```
error:
```
error: SchemaError(xxx.crd.path.field): array should have exactly one sub-item
```
Issue:
1、Not able to edit or delete my crd
2、Not able to apply any resources to k8s

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:18:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by eddiezane** [comment]
@leviisfool please provide an example CRD to reproduce (that we can copy and paste) and the error message in full.

Also please check if this issue occurs on a [supported version](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl).

**Comment by brianpursley** [comment]
Possible additional context for this error message:
https://github.com/kubernetes/kubernetes/blob/dd1709ba46580af290712b0eca12acd00a78789d/vendor/k8s.io/kube-openapi/pkg/util/proto/document.go#L214-L218

**Comment by leviisfool** [comment]
crd sample
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                endpoints:
                  items:
                    type: object
                  type: array
                  x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
      - ct
```

The problem only appears on version v1.18.12, it does not exists on version v1.19.7.
It was fixed.
