### ISSUE TITLE
Duplicate port name across containers does not trigger error

### ISSUE THREAD

**Issue by loozhengyuan** [kubernetes/kubectl#1048]
**What happened**:

When creating containers with duplicate port names, no error was returned.

**What you expected to happen**:

Expected an error to be returned.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repro
  labels:
    app: repro
spec:
  selector:
    matchLabels:
      app: repro
  template:
    metadata:
      labels:
        app: repro
    spec:
      containers:
        - name: db
          image: nginx
          ports:
            - containerPort: 5432
              name: https  # duplicate
              protocol: TCP
        - name: web
          image: nginx
          ports:
            - containerPort: 8080
              name: https  # duplicate
              protocol: TCP
```

```console
$ kubectl apply -f repro.yaml
deployment.apps/repro created
```

**Anything else we need to know?**:

The actual symptom I had was that running `kubectl port-forward` on a Service with duplicate port names causes it to resolve to the wrong port (if the wrong port is ordered before the correct one). The `kubectl port-forward` command calls [LookupContainerPortNumberByName](https://github.com/kubernetes/kubernetes/blob/dfc91819b78e7dbf56194f50eff4c19c9fecd01b/staging/src/k8s.io/kubectl/pkg/util/pod_port.go#L26) to derive the port number. In my case, it forwarded port `5432` of the `db` container because it was the first container and the first port with matching `targetPort` name of `https`.

I noted that duplicate port names _within_ a container will return an error message like below:

```
The Deployment "repro" is invalid: spec.template.spec.containers[0].ports[1].name: Duplicate value: "https"
```

However, when port name duplicates exists _between_ containers, no error messages will be returned. This causes an issue when running `kubectl port-forward` because it seems to expect port names to be unique within a Pod.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.2100", GitCommit:"36d0b0a39224fef7a40df3d2bc61dfd96c8c7f6a", GitTreeState:"clean", BuildDate:"2021-03-16T09:15:29Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): MacOS Big Sur
