### ISSUE TITLE
certificate-authority-data not merged with KUBECONFIG env-var

### ISSUE THREAD

**Issue by OneCricketeer** [kubernetes/kubectl#1054]
**How to reproduce it (as minimally and precisely as possible)**:

`k3d` cluster created on custom network (see my commands [here](https://github.com/kubernetes-sigs/kubefed/issues/1412#issuecomment-840851315))

Default `k3d` kube config uses host network `http://0.0.0.0:<random port>`; `docker ps` shows port forward `0.0.0.0:<random port>->6443/tcp`, and this is reflected in the `kubectl config view --minify` after creating a k3d cluster.  

Want to use Flux resources, which are bundled in the `docker.io/fluxcd/flux-cli` image, so trying to interact with `k3d` api-server in this container on same network. In order to do this, seems I need to override `cluster.server` kubeconfig (_aside_ if there is another way to explicitly set only this without merging a whole kubeconfig, let me know)

So, define a minimal kubeconfig with only the values I want to override

<details><summary>Minimal kubeconfig (click to expand)</summary>
<p>

```yml
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://k3d-ctrl-server-0:6443
  name: k3d-ctrl
- cluster:
    server: https://k3d-worker-server-0:6443
  name: k3d-worker
current-context: k3d-ctrl
```

</p>
</details>

And mount the kubeconfig I use on the host, which looks like this 

<details><summary>Host kubeconfig (click to expand)</summary>
<p>

```yml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://0.0.0.0:60507
  name: k3d-ctrl
contexts:
- context:
    cluster: k3d-ctrl
    user: admin@k3d-ctrl
  name: k3d-ctrl
current-context: k3d-ctrl
kind: Config
preferences: {}
users:
- name: admin@k3d-ctrl
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

</p>
</details>

(there is also a `k3d-worker` context and user, but can be ignored for this issue, IMO)

```sh
$ docker run --rm -ti --network=k3d-bridge --entrypoint=ash -v $HOME/.kube/config:/root/.kube/config -v $PWD/kubectl-e2e-docker.yml:/tmp/kubeconfig.yml -e KUBECONFIG='/tmp/kubeconfig.yml:/root/.kube/config' fluxcd/flux-cli:v0.13.4
```

```
# kubectl config view --minify
apiVersion: v1
clusters:
- cluster:
    server: https://k3d-ctrl-server-0:6443
  name: k3d-ctrl
contexts:
- context:
    cluster: k3d-ctrl
    user: admin@k3d-ctrl
  name: k3d-ctrl
current-context: k3d-ctrl
kind: Config
preferences: {}
users:
- name: admin@k3d-ctrl
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

**What happened**:

The merge worked for `cluster.server` URI, but `cluster.certificate-authority-data` is missing.

`kubectl` commands generated this cert error

> `Unable to connect to the server: x509: certificate signed by unknown authority`

**What you expected to happen**:

The CA data should be merged in (last file wins? not completely familiar with the [full merging logic](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files)), and I don't have to use `--insecure-skip-tls-verify`

Docs seem to suggest that the first file to contain that key should get merged in....

> The first file to set a particular **value or map key** wins

**Anything else we need to know?**:

**Environment**: macOS 10.15.7 
- Kubernetes client and server versions (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10+k3s1", GitCommit:"72e8196c9b9eb277f56951db6d2d9e5f9f70feac", GitTreeState:"clean", BuildDate:"2021-04-16T18:36:38Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
