### ISSUE TITLE
Be in trouble to get kubeconfig information from kubectl to custom proxy api

### ISSUE THREAD

**Issue by aroundude** [kubernetes/kubectl#1062]
Currently, I am developing kubernetes api proxy server by golang.
the proxy server is gonna be responsible for my custom authentication.
the flow is as below.

`kubectl -> my proxy api(process authentication) -> kubeapiserver`

and local kubeconfig is as below.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {cert...}
    server: http://localhost:8080
  name: aaa
contexts:
- context:
    cluster: aaa
    user: aaa
  name: aaa
current-context: aaa
kind: Config
preferences: {}
users:
- name: {name}
  user:
    token: {token...}
```

I wanna **get cluster information and users information such as _context name or user token_**,
and I thought there should be in the request header or anywhere from request.
But I can't get data from request and anywhere.
