### ISSUE TITLE
`kubectl apply` and `kubectl diff` ignores changing serviceAccountName to null/empty

### ISSUE THREAD

**Issue by wc-s** [kubernetes/kubectl#1064]
**What happened**:
1. used `kubectl apply` on a deployment yaml to deploy a pod with `serviceAccountName: foo`
2. edited the yaml to remove the `serviceAccountName: foo` line
3. now, if I do `kubectl diff` on the yaml, kubectl will act as if there is no diff; if I do a `kubectl apply`, k8s won't apply any change (whereas I'd expect it to revert the serviceAccountName to `default`)

**What you expected to happen**:
- I'd expect the removal of the `serviceAccountName` line to show up in `kubectl diff`
- If I remove the `serviceAccountName` specification from the deployment yaml, and if I do a `kubectl apply`, I'd expect the `serviceAccountName` field to revert to the default of `default`

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply this yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytest
spec:
  replicas: 1
  selector:
    matchLabels:
      for: test
      app: alpine
  template:
    metadata:
      labels:
        for: test
        app: alpine
    spec:
      serviceAccountName: foo
      containers:
      - name: alpine
        image: alpine
        command:
          - sleep
        args:
          - infinity
```
2. remove the `serviceAccountName: foo` line from the yaml
3. now try to do a `kubectl apply` or `kubectl diff` against the changed yaml file

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
client: 1.20.1
server: 1.20.6

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
