### ISSUE TITLE
PersistentVolumeClaim resources not returned by "kubectl get all --namespace myapp"

### ISSUE THREAD

**Issue by pcgeek86** [kubernetes/kubectl#1065]
**What happened**: When I run the `kubectl get all` command on a specific namespace, `PersistentVolumeClaim` resources are not returned. 

**What you expected to happen**: `PersistentVolumeClaim` resources are returned when requesting `all` resources from a namespace.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run `kubectl create namespace pwsh`
1. Apply configuration below
1. Run `kubectl get all --namespace pwsh`

```
apiVersion: v1
kind: Pod
metadata:
  namespace: pwsh
  name: pwsh
  labels:
    username: trevorsullivan
spec:
  containers:
  - name: pwsh
    image: microsoft/powershell:latest
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    command:
      - pwsh
    args:
      - -Command
      - Start-Sleep
      - -Seconds 1000
    volumeMounts:
      - mountPath: /data
        name: pwshclaim
  volumes:
    - name: pwshclaim
      persistentVolumeClaim:
        claimName: pwshclaim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pwsh
  name: pwshclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): (see below)
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Windows 10 Insiders Build 21387

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

Possibly related to #151
