### ISSUE TITLE
Kubectl infinitely hangs when deleting an in-use PersistentVolumeClaim

### ISSUE THREAD

**Issue by pcgeek86** [kubernetes/kubectl#1068]
**What happened**:

This command resulted in an infinitely hung shell. I hit CTRL + C to cancel execution, and tried running it again, which resulted in the same behavior.

```
C:\kube\storage> kubectl delete pvc pwshpvclaim
persistentvolumeclaim "pwshpvclaim" deleted
C:\kube\storage> kubectl delete pvc pwshpvclaim
persistentvolumeclaim "pwshpvclaim" deleted
```

**What you expected to happen**:

I could envision one of two things occurring:

1. An error occurs, indicating that the PVC cannot be removed properly, because it's in-use, or ...
2. The PVC is properly deleted

**How to reproduce it (as minimally and precisely as possible)**:

I was able to reproduce this issue by deleting all the resources, starting fresh, and following the below commands.

1. Run kubectl apply with the file below
2. Run `kubectl delete pvc pwshpvclaim`

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: amazonebsio1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "30"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Pod
metadata:
  name: pvpwsh
spec:
  volumes:
    - name: pwshdata
      persistentVolumeClaim:
        claimName: pwshpvclaim
  containers:
  - name: pwsh
    image: microsoft/powershell
    command:
      - pwsh
    args:
      - -Command
      - Wait-Event
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /bacon
        name: pwshdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pwshpvclaim
spec:
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  storageClassName: amazonebsio1
  accessModes:
    - ReadWriteOnce
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Windows 10 Insiders 21387

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

Also reproduced with newer version of kubectl:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
