### ISSUE TITLE
Create PV and PVC in imperative way

### ISSUE THREAD

**Issue by nurhun** [kubernetes/kubectl#1073]
**What would you like to be added**:
Create PV and PVC in imperative way

**Why is this needed**:
Automating, instead of pulling remote yaml

**Comment by brianpursley** [comment]
@nurhun As a workaround, you can do things imperatively using `kubectl apply` with a heredoc, like this:

```
kubectl apply -f - << EOF
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: pvg-k8s-pod-priority
EOF
```

You could adapt that example for PV and PVC.
