### ISSUE TITLE
inconsistent/incorrect validation

### ISSUE THREAD

**Issue by m1stermanager** [kubernetes/kubectl#1141]
**What happened**:
I am using AKS. I have installed kubectl via the instructions for ubuntu from kubernetes.io

the cluster kubernetes version is 1.20.9
my kubectl version I have installed is also 1.20.9

I like AKS and kubectl following the instructions laid out in the AKS documentation. I can get statuses, versions, etc

I select to deploy the sample application in AKS, I take the yaml and save it to a file on my local machine. I run `kubectl apply -f <filename>` and receive: `error: error validating "<filename>": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false`

If I strip the file down to JUST a namespace, I receive the same error. the file now consists of 

```
- apiVersion: v1
  kind: Namespace
  metadata:
    name: azure-vote-1636046345437
  spec:
    finalizers:
      - kubernetes
```
**What you expected to happen**:
It should've applied the configuration. this functions via the azure UI 
**How to reproduce it (as minimally and precisely as possible)**:
have AKS running 1.20.9, have kubectl 1.20.9, try to apply the above configuration.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T21:01:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"ed93e7ea8f833824d05578765c2ad3efbebbfebe", GitTreeState:"clean", BuildDate:"2021-10-21T03:31:08Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- AKS
- OS (e.g: `cat /etc/os-release`):
ubuntu 18.04 (through wsl2)

**Comment by brianpursley** [comment]
Your yaml file should not have the `- ` on line 1.

Try this instead:
```
apiVersion: v1
kind: Namespace
metadata:
  name: azure-vote-1636046345437
spec:
  finalizers:
    - kubernetes
```
