### ISSUE TITLE
`kubectl apply -k` with `helmCharts` cannot run

### ISSUE THREAD

**Issue by anvouk** [kubernetes/kubectl#1144]
**What happened**:
Can't pass the `kustomize` flag `--enable-helm` to `kubectl apply -k`

**What you expected to happen**:
Helm chart gets built and deployed.

**How to reproduce it (as minimally and precisely as possible)**:
1. create this kustomize file: `test/kustomization.yaml`
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: minecraft
    releaseName: test
    version: 3.1.3
    repo: https://itzg.github.io/minecraft-server-charts
```

2. Try to deploy it with  `kubectl.exe apply -k test`
3. This happens:
```
error: trouble configuring builtin HelmChartInflationGenerator with config: `
name: minecraft
releaseName: test
repo: https://itzg.github.io/minecraft-server-charts
version: 3.1.3
`: must specify --enable-helm
```

However, I found no way to pass `--enable-helm`

**Anything else we need to know?**:

using `kustomize build --enable-helm test` (version `v4.1.3`) works as expected.

The doc about `helmCharts` is very minimal. is there some way to enable `kustomize` flags globally from `kubectl`?

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: `docker desktop k8s on WSL`
- OS (e.g: `cat /etc/os-release`): `windows 10`

**Comment by werwolfby** [comment]
Have the same question.
Is it a new feature? Cause someone definitely tried it before 😏.

**Comment by KnVerey** [comment]
You're right that `kubectl apply -k` does not expose additional Kustomize-specific flags. I believe it intentionally only supports the simple case, for the sake of the simplicity of `apply` options. If you need to configure Kustomize behavior with additional flags, you can use `kubectl kustomize` and standalone `kustomize` instead.

/close

**Comment by anvouk** [comment]
Thanks, I managed to get it to work with the following:
```
kubectl kustomize test --enable-helm | kubectl apply -f -
```

**Comment by yossicohn** [comment]
@KnVerey the proposed usage with `kubectl apply -f -` would work, but that would not be enough with ArgoCD ...which is my case

**Comment by KnVerey** [comment]
I'm not familiar enough with ArgoC to advise, though it appears to me that it supports [arbitrary Kustomize versions](https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/), which would imply standalone Kustomize support. I maintain that `kubectl apply -k` must not be modified to support Kustomize-specific flags.

**Comment by zswanson** [comment]
@yossicohn argocd supports this via an option in the argocd CM. 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # enables a kustomization option that can work with remote helm repos
  kustomize.buildOptions: --enable-helm
```
