### ISSUE TITLE
Not correct output when run  --dry-run=client --command -- sleep xx -o yaml

### ISSUE THREAD

**Issue by patsevanton** [kubernetes/kubectl#1148]
Hello! May be Feature request.
**Env**: `minikube v1.23.2`

**kubectl version**
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**kubectl run busybox --image=busybox --dry-run=client --command -- sleep 1000 -o yaml**
`pod/busybox created (dry run)`

**kubectl run busybox --image=busybox --dry-run=client -o yaml --command -- sleep 1000**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - sleep
    - "1000"
    image: busybox
    name: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```
