### ISSUE TITLE
Network errors with many resources being applied greater than soft file descriptor limit

### ISSUE THREAD

**Issue by jgminer** [kubernetes/kubectl#1152]
**What happened**:
When running kubectl with several hundred resources, we started seeing interesting behavior:

```
error when deleting "ingresses.yaml": Delete "https://SOME_ID.TEST.SOME_REGION.eks.amazonaws.com/apis/networking.k8s.io/v1/namespaces/default/ingresses/minimal-ingress-295": dial tcp: lookup SOME_ID.TEST.SOME_REGION.eks.amazonaws.com: no such host
```

We were able to reproduce the apparent issue by creating a bunch of "dummy" resources - in this case ingresses - and applying them all. 

If the number of resources is greater than the currently configured file descriptor soft limit, you should start seeing errors.

If you increase your soft limit, the errors will not appear.

Interestingly, we created this test using namespaces and once above the soft limit we did not experience errors, just a marked slowdown in the CLI.

**What you expected to happen**:
No errors or performance impact with many resources (ideally). No need to increase file descriptor soft limit.

**How to reproduce it (as minimally and precisely as possible)**:
1. Check ulimit count `ulimit -n`
1. Create number of resources in a yaml (apparently resources need to be ingress/daemonset/deployment in our case) > ulimit by creating a file with the following content called `ingresses-test.yaml.jinja`
  ```
  {% for iter_value in range(300) %}apiVersion: v1
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: minimal-ingress-{{ iter_value }}
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
    - http:
        paths:
        - path: /testpath/{{ iter_value }}
          pathType: Prefix
          backend:
            service:
              name: test
              port:
                number: 60{{ iter_value }}
  ---
  {% endfor %}
  ```
3. Generate the yaml `jinja ingresses-test.yaml.jinja -o ingresses.yaml`
4. Apply the yaml `kubectl apply -f ingresses.yaml`
5. Experience unexpected network errors

WORKAROUND:
1. Increase soft limit for your OS (for example macOS):
`sudo launchctl limit maxfiles 10000 200000`
1. Completely re-launch your terminal, confirm ulimit actually increased with `ulimit -n`
1. Run kubectl apply step from above
1. There should be no errors

**Anything else we need to know?**:
* Use `lsof -a -p PROCESS_ID` to see the network connections in TCP CLOSED state (not sure why this would still cause issues - maybe they aren't getting cleaned up completely). Add `wc -l` to see the count grow as you run `kubectl apply` until reaching the soft limit.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
  - AWS EKS 1.21 w/EC2 Node Groups
- OS (e.g: `cat /etc/os-release`):
  - macOS Big Sur 11.6.1
