### ISSUE TITLE
`kubectl create -k` doesn't support kustomizations including helm charts

### ISSUE THREAD

**Issue by rcmorano** [kubernetes/kubectl#1162]
**What would you like to be added**:

`kubectl create -k` support for `--helm-chart` or just have it enabled by default.

**Why is this needed**:

I've faced a dead end while trying to deploy fission [0] helm chart using a `kustomization` where `kubectl apply` won't be able to apply my manifest due to to some internal limitation [1] and the only way is to workaround it seems to be using `kubectl create`; which doesn't support support helm charts [2] (unlike `kubectl kustomize`, which does, but then I face the `apply` problem again :)).

**How to reproduce**:

* Create this `kustomization.yaml`:
```
bases:
- https://github.com/fission/fission/crds/v1?ref=v1.15.1

helmCharts:
- name: fission-all
  valuesFile: helm-values.yaml
  namespace: fission
  releaseName: init0
  version: v1.15.1
  repo: https://fission.github.io/fission-charts/
```
* Try to apply it, ie, using `kubectl kustomize --enable-helm . | kubectl apply -f -`. You will receive the size limit error [3]
* Try to create it using `kubectl create -k .` you will receive [2]

[0] https://github.com/fission/fission/tree/master/charts/fission-all
[1] https://github.com/fission/fission/issues/2081
[2] 
```
kubectl create -k . 
error: trouble configuring builtin HelmChartInflationGenerator with config: `
name: fission-all
namespace: fission
releaseName: init0
repo: https://fission.github.io/fission-charts/
valuesFile: helm-values.yaml
version: v1.15.1
`: must specify --enable-helm
```
[3] `The CustomResourceDefinition "environments.fission.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`
