### ISSUE TITLE
kubectl convert should return error when out-version is an invalid value

### ISSUE THREAD

**Issue by shiywang** [kubernetes/kubectl#119]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.2069+b518a80cef0302-dirty", GitCommit:"b518a80cef03022132e701b73da43dc93f956eaa", GitTreeState:"dirty", BuildDate:"2017-11-02T06:08:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:

```
➜  amd64 git:(convert_fix) ✗ kubectl convert -f test.yaml --local --output-version=no/exist 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: php-apache
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: php-apache
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0
```

**What you expected to happen**:
```
➜  amd64 git:(convert_fix) ✗ ./kubectl convert -f test.yaml --local --output-version=no/exist
error: 'no/exist' is not a registered version.
See 'kubectl convert -h' for help and examples.
```

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
