### ISSUE TITLE
Creating context blows out custom adds to .kube/config

### ISSUE THREAD

**Issue by rwxrob** [kubernetes/kubectl#1203]
**What happened**:

1. Added OIDC provider information directly to `~/.kube/config` in
   unrelated sections
1. Successfully use OIDC information to query OIDC provider and populate
   token information under `users` section
1. Automatically add contexts for our clusters
1. Verify with `kubectl get pods`, etc.
1. (Work without problems for days)
1. Add a context with `kubectl set-context ...`
1. Notice `kubectl-login` now fails
1. Inspect `~/.kube/config` and discover OIDC config is now gone

**What you expected to happen**:

I expect anything using `~/.kube/config` to respect the existing data
that is in it and not blow it out (which applications like `kind` do
correctly by using the `yaml:",inline"` approach). Forcing separate
configuration files for other user configurations is problematic. Such
information should be safe in that file and applications should only use
what they require.

**Anything else we need to know?**:

**Environment**:

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

Minikube/Kind local setup.

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by rwxrob** [comment]
1. Add anything by hand to `~/.kube/config`
2. `kubectl set-context ...` to add new context
3. Open `~/.kube/config` and see your adds are now missing

**Comment by mpuckett159** [comment]
Apologies but I'm not able to reproduce this as described. I've included the steps I've taken to attempt to reproduce this at the end of this comment. All values copied from [kubernetes docs](https://kubernetes.io/docs/reference/access-authn-authz/authentication/) so they aren't real.

Couple questions:
1. While testing I noticed that it will remove invalid keys. So for example if I set something like
```
users: 
- name: test-oidc-user
  users:
...
```
is set, it will remove the `users` key and all configurations under it and replace it with a null valued `user` key.
2. Just in case, make sure you're actually saving your manual changes to your kubeconfig. I have pretty much all my editors set to save constantly and always forget to save when I'm not using my computer.

If it is not either of these and you can provide me a more exact reproduction method I can work on tracking down the source of the problem.

## Reproduction steps
Version (couldn't get brew to cooperate so I just checked out the specified commit and built it manually)
```
kubernetes on 🌱HEAD (e6c093d) [$] via 🐹 v1.18.1 on ☁️  (us-west-2) 
❯ ./_output/local/bin/darwin/amd64/kubectl version                                                                                     
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-04-27T20:53:35Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
```

Starting config added manually:
```
apiVersion: v1
clusters:
- cluster:
    server: https://1.1.1.1
  name: fake-cluster
contexts: null
current-context: ""
kind: Config
preferences: {}
users: 
- name: test-oidc-user
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: 1db158f6-177d-4d9c-8a8b-d36869918ec5
        id-token: eyJraWQiOiJDTj1vaWRjaWRwLnRyZW1vbG8ubGFuLCBPVT1EZW1vLCBPPVRybWVvbG8gU2VjdXJpdHksIEw9QXJsaW5ndG9uLCBTVD1WaXJnaW5pYSwgQz1VUy1DTj1rdWJlLWNhLTEyMDIxNDc5MjEwMzYwNzMyMTUyIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL29pZGNpZHAudHJlbW9sby5sYW46ODQ0My9hdXRoL2lkcC9PaWRjSWRQIiwiYXVkIjoia3ViZXJuZXRlcyIsImV4cCI6MTQ4MzU0OTUxMSwianRpIjoiMm96US15TXdFcHV4WDlHZUhQdy1hZyIsImlhdCI6MTQ4MzU0OTQ1MSwibmJmIjoxNDgzNTQ5MzMxLCJzdWIiOiI0YWViMzdiYS1iNjQ1LTQ4ZmQtYWIzMC0xYTAxZWU0MWUyMTgifQ.w6p4J_6qQ1HzTG9nrEOrubxIMb9K5hzcMPxc9IxPx2K4xO9l-oFiUw93daH3m5pluP6K7eOE6txBuRVfEcpJSwlelsOsW8gb8VJcnzMS9EnZpeA0tW_p-mnkFc3VcfyXuhe5R3G7aa5d8uHv70yJ9Y3-UhjiN9EhpMdfPAoEB9fYKKkJRzF7utTTIPGrSaSU6d2pcpfYKaxIwePzEkT4DfcQthoZdy9ucNvvLoi1DIC-UocFD8HLs8LYKEqSxQvOcvnThbObJ9af71EwmuE21fO5KzMW20KtAeget1gnldOosPtz1G5EwvaQ401-RPQzPGMVBld0_zMCAwZttJ4knw
        idp-certificate-authority: /root/ca.pem
        idp-issuer-url: https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP
        refresh-token: q1bKLFOyUiosTfawzA93TzZIDzH2TNa2SMm0zEiPKTUwME6BkEo6Sql5yUWVBSWpKUGphaWpxSVAfekBOZbBhaEW+VlFUeVRGcluyVF5JT4+haZmPsluFoFu5XkpXk5BXq
      name: oidc
```

Command:
```
kubernetes on 🌱HEAD (e6c093d) [$] via 🐹 v1.18.1 on ☁️  (us-west-2) 
❯ ./_output/local/bin/darwin/amd64/kubectl config set-context test-fake-set-context1 --cluster=fake-cluster --user=developer --namespace=fake-ns
Context "test-fake-set-context1" created.
```

Resulting config:
```
apiVersion: v1
clusters:
- cluster:
    server: https://1.1.1.1
  name: fake-cluster
contexts:
- context:
    cluster: fake-cluster
    namespace: fake-ns
    user: developer
  name: test-fake-set-context1
current-context: ""
kind: Config
preferences: {}
users:
- name: test-oidc-user
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: 1db158f6-177d-4d9c-8a8b-d36869918ec5
        id-token: eyJraWQiOiJDTj1vaWRjaWRwLnRyZW1vbG8ubGFuLCBPVT1EZW1vLCBPPVRybWVvbG8gU2VjdXJpdHksIEw9QXJsaW5ndG9uLCBTVD1WaXJnaW5pYSwgQz1VUy1DTj1rdWJlLWNhLTEyMDIxNDc5MjEwMzYwNzMyMTUyIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL29pZGNpZHAudHJlbW9sby5sYW46ODQ0My9hdXRoL2lkcC9PaWRjSWRQIiwiYXVkIjoia3ViZXJuZXRlcyIsImV4cCI6MTQ4MzU0OTUxMSwianRpIjoiMm96US15TXdFcHV4WDlHZUhQdy1hZyIsImlhdCI6MTQ4MzU0OTQ1MSwibmJmIjoxNDgzNTQ5MzMxLCJzdWIiOiI0YWViMzdiYS1iNjQ1LTQ4ZmQtYWIzMC0xYTAxZWU0MWUyMTgifQ.w6p4J_6qQ1HzTG9nrEOrubxIMb9K5hzcMPxc9IxPx2K4xO9l-oFiUw93daH3m5pluP6K7eOE6txBuRVfEcpJSwlelsOsW8gb8VJcnzMS9EnZpeA0tW_p-mnkFc3VcfyXuhe5R3G7aa5d8uHv70yJ9Y3-UhjiN9EhpMdfPAoEB9fYKKkJRzF7utTTIPGrSaSU6d2pcpfYKaxIwePzEkT4DfcQthoZdy9ucNvvLoi1DIC-UocFD8HLs8LYKEqSxQvOcvnThbObJ9af71EwmuE21fO5KzMW20KtAeget1gnldOosPtz1G5EwvaQ401-RPQzPGMVBld0_zMCAwZttJ4knw
        idp-certificate-authority: /root/ca.pem
        idp-issuer-url: https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP
        refresh-token: q1bKLFOyUiosTfawzA93TzZIDzH2TNa2SMm0zEiPKTUwME6BkEo6Sql5yUWVBSWpKUGphaWpxSVAfekBOZbBhaEW+VlFUeVRGcluyVF5JT4+haZmPsluFoFu5XkpXk5BXq
      name: oidc
```
