### ISSUE TITLE
no kind "Pod" is registered for version "v1" in scheme

### ISSUE THREAD

**Issue by jjkim0816** [kubernetes/kubectl#1212]
Hi,
I executed command $kubectl logs [pod name] [container_name], but I got a error message.
"no kind "Pod" is registered for version "v1" in scheme "vendor/k8s.io/client-go/tools/clientcmd/api/latest/latest.go:50"
How to solve it. Please give me answer genius bros~.

"Pod" is capital. It is the first part of "~/.kube/config"
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-05-06T01:51:35Z"
```

It is my kubectl version.
```
$ kubectl version --client --output=yaml
clientVersion:
  buildDate: "2022-05-03T13:46:05Z"
  compiler: gc
  gitCommit: 4ce5a8954017644c5420bae81d72b09b735c21f0
  gitTreeState: clean
  gitVersion: v1.24.0
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
```
