### ISSUE TITLE
Weird behaviour with `--prune` when updating immutable labels with `--force`

### ISSUE THREAD

**Issue by rrey-aviatrix** [kubernetes/kubectl#1239]
**What happened**:

I recently did an update of manifests created by cdk8s v1.x to v2.x.
Among the changes in the manifests, the labels create by the tool changed their name.
I am using the `--prune` option and I had a weir behaviour at apply, where resources were updated and then pruned, leaving the namespace empty.

Output of the  apply command:
```
$ kubectl apply -f deploy_2.yml --prune -l another_app=nginx --force
deployment.apps/nginx-deployment configured
deployment.apps/nginx-deployment pruned
```
The `--force` is here to update the label (immutable).
Note that the label selection in the arg uses the new labels, not the old one.

**What you expected to happen**:

I expected the deployment to be updated and *not* pruned.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the following manifest:
```
# deploy.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
     app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
```

Then apply the following one (same manifest but labels are updated):

```
# deploy_2.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    another_app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      another_app: nginx
  template:
    metadata:
      labels:
        another_app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
```

kubectl command used is:
```
kubectl apply -f deploy_2.yml --prune -l another_app=nginx --force
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11", GitCommit:"5824e3251d294d324320db85bf63a53eb0767af2", GitTreeState:"clean", BuildDate:"2022-06-16T05:39:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Detected on EKS 1.21 with kubectl running in Github Actions (ubuntu-latest) 
Reproduced on docker-desktop (MacOS)
