### ISSUE TITLE
Memory request/limit not correct when applying with `Gi`

### ISSUE THREAD

**Issue by Uranium2** [kubernetes/kubectl#1250]
**What happened**:
I am not getting the correct memory requested in memory request/limits when using `Gi` notation. I get `157286400m` for `0.15Gi` in request and `188743680m` for `0.18Gi` in limits

**How to reproduce it (as minimally and precisely as possible)**:

```YAML
apiVersion: batch/v1
kind: Job
metadata:
  name: job-testing
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: job-testing
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - python3 main.py
        env:
        - name: DEPLOY_ENV
          value: prd
        image: <IMAGE>
        imagePullPolicy: Always
        name: job-testing
        resources:
          limits:
            cpu: 0.18
            memory: 0.18Gi
          requests:
            cpu: 0.15
            memory: 0.15Gi
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: <DTR_SERVER>
      restartPolicy: Never
      securityContext:
        fsGroup: 11111
        runAsGroup: 11111
        runAsUser: 11111
```

My original YAML has volumes and secrets which i stripped here and using a corporate DTR/docker Image

`kubectl apply -n my-namespace -f job.yaml`

**Anything else we need to know?**:
The YAML file is generated with [kubernetes-client ](https://github.com/kubernetes-client/python/) in python. But when I print it, I get expected values of `0.15Gi` and `0.18Gi`. And the error is the same when the package applies the configuration or that I apply myself the YAML file. I am wondering[ if this could be changed by the server.](https://github.com/kubernetes-client/python/issues/1783)

**Environment**:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-mirantis-1", GitCommit:"c0557aa1a9571c353503500cb7130a2f491d073f", GitTreeState:"clean", BuildDate:"2021-09-18T04:05:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by eddiezane** [comment]
> I am not getting the correct memory requested in memory request/limits

Could you please provide more information about where you are seeing this and what you are expecting to see?

I don't think that `m` (lowercase m) is a valid value when dealing with bytes. `m` is used for milicpu units.

Check out the documentation for this type https://github.com/kubernetes/kubernetes/blob/93054957c13a5398a1b0eabb3d9c77f896e46093/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L31.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

**Comment by brianpursley** [comment]
My attempt to reproduce below.  I'm not seeing the same numbers:

Script:
```
kubectl apply -f - <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.30.0
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(1000)"]
          resources:
            limits:
              cpu: 0.18
              memory: 0.18Gi
            requests:
              cpu: 0.15
              memory: 0.15Gi
      restartPolicy: Never
  backoffLimit: 0
EOF

kubectl describe job pi
```

Actual Output:
```
job.batch/pi created
Name:           pi
Namespace:      default
Selector:       controller-uid=230a3b9e-0a05-4c4d-ae4e-25a51bb14881
Labels:         controller-uid=230a3b9e-0a05-4c4d-ae4e-25a51bb14881
                job-name=pi
Annotations:    <none>
Parallelism:    1
Completions:    1
Start Time:     Wed, 17 Aug 2022 14:29:36 -0400
Pods Statuses:  1 Active / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=230a3b9e-0a05-4c4d-ae4e-25a51bb14881
           job-name=pi
  Containers:
   pi:
    Image:      perl:5.30.0
    Port:       <none>
    Host Port:  <none>
    Command:
      perl
      -Mbignum=bpi
      -wle
      print bpi(1000)
    Limits:
      cpu:     180m
      memory:  193273528320m
    Requests:
      cpu:        150m
      memory:     161061273600m
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  0s    job-controller  Created pod: pi-bxjtj
```

It looks like it is doing this math:
.18 x 1024 x 1024 x 1024 = 193273528.32 = 193273528320m
.15 x 1024 x 1024 x 1024 = 161061273.6 = 161061273600m

I see the same numbers if I get the job or pod using `-o yaml`
```
    resources:
      limits:
        cpu: 180m
        memory: 193273528320m
      requests:
        cpu: 150m
        memory: 161061273600m
```

@Uranium2 do you get a different result than the above?
