### ISSUE TITLE
`kubectl kustomize` doesn't support replacements

### ISSUE THREAD

**Issue by alanwu4321** [kubernetes/kubectl#1277]
**What happened**:
`kubectl kustomize` throws `Error: json: unknown field "replacements"`

**What you expected to happen**:
`kubectl kustomize` builds successfully with `replacemnts`

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- source:
    kind: Deployment
    fieldPath: metadata.name
  targets:
  - select:
      name: my-resource
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): `GitVersion:"v1.21.4",`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
