### ISSUE TITLE
matchLabelKeys in topologySpreadConstraints doesn't not print anything in kubectl describe

### ISSUE THREAD

**Issue by liboz** [kubernetes/kubectl#1283]
### What happened?

I used `kubectl describe` on a pod with `topologySpreadConstraints`'s matchLabelKeys applied. I have the featuregate `MatchLabelKeysInPodTopologySpread` applied

### What did you expect to happen?

I expect some printed output that indicates that the config has been applied. I expect the code needs to be updated here https://github.com/kubernetes/kubernetes/blob/23a4920d83559ba803629512c8a02630e5fdc0a6/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L895

### How can we reproduce it (as minimally and precisely as possible)?

Use `kubectl describe` on a pod with `topologySpreadConstraints`'s matchLabelKeys applied

### Kubernetes version

1.25

### Cloud provider

k3s baremetal

**Comment by ardaguclu** [comment]
@liboz after investigating the issue, I noticed that `matchlabelskeys` are merged in `labelselector`(by ANDing) and we are already showing `labelselector` in describe command. As far as I understand, if `matchlabelkeys` is applied for your resource, it should be seen in `Topology Spread Constraints` field.

**Comment by liboz** [comment]
Here's a reproduceable test on GKE (I originally was using k3s): 

1. Created a cluster on GKE with this command: `gcloud container clusters create test-cluster --cluster-version=1.25 --release-channel=rapid --zone=us-central1-a --machine-type=e2-small --num-nodes=2  --enable-kubernetes-alpha --no-enable-autorepair --no-enable-autoupgrade`
1. Run `kubectl apply -f test.yaml` where the contents of `test.yaml` are:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ubuntu
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          matchLabelKeys:
            - app
            - pod-template-hash
      containers:
        - name: ubuntu
          image: ubuntu
          command:
            - "sleep"
            - "604801"
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi
```
1. Run `kubectl describe pod` on one of the pods that get created

I get output like this:
```
Node-Selectors:               <none>
Tolerations:                  node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Topology Spread Constraints:  kubernetes.io/hostname:DoNotSchedule when max skew 1 is exceeded
```

As you can see the parts about `app`, `pod-template-hash` do not display for me. The result of my `kubectl version` command is 
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0-gke.1100", GitCommit:"eac9e5e684229c0f820abb108048cff3b91440d4", GitTreeState:"clean", BuildDate:"2022-09-05T09:29:20Z", GoVersion:"go1.19 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
so I'm on the right version for `kubectl` I believe.

Are you seeing something different?
