### ISSUE TITLE
kubectl not apply changing spaces in file

### ISSUE THREAD

**Issue by sobolevskaya-k** [kubernetes/kubectl#1288]
**What happened**:  We made a mistake in specifying the version of the image in deployment

`
    containers:
      image: { IMAGE_NAME }:"MISTAKE_SPACE"{ IMAGE_VERSION }
`
we tried to fix it - removed the space and using the command - `kubectl apply -f deployment.yaml`, but the changes were not applied.

**What you expected to happen**:
we expected, what "kubectl" noticed the change in spaces and applied it.

**How to reproduce it (as minimally and precisely as possible)**:
**_deployment with mistake_**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx: 1.14.2
        ports:
        - containerPort: 80
```

**_fixed deployment_**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
