### ISSUE TITLE
Kubectl doesn't allow "describe" for resource with slash in the name

### ISSUE THREAD

**Issue by ianburrell** [kubernetes/kubectl#1304]
**What happened**:

Tried to do "describe" on PersistentVolumeClaim with slash in the name (clickhouse/jk-storage-chi-dev-clickhouse-comscore-0-1-0). These are created by the clickhouse operator.

With type/resource syntax, it gave error about not having more than one slash. With the "type resource" syntax, it gave error about specifying resource type as separate argument.

**What you expected to happen**:

Describing the resource.

**How to reproduce it (as minimally and precisely as possible)**:

$ kubectl describe pvc/clickhouse/jk-storage-chi-dev-clickhouse-comscore-0-1-0
error: arguments in resource/name form may not have more than one slash

$ kubectl describe pvc clickhouse/jk-storage-chi-dev-clickhouse-comscore-0-1-0
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'kubectl get resource/<resource_name>' instead of 'kubectl get resource resource/<resource_name>'

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 

Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.20.15-eks-6d3986b

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): macOS 12.6

**Comment by ardaguclu** [comment]
This is not allowed naming because it corrupts the resource/name pattern. I tried to create a dummy resource;

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test/task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

and server returned;

```
error: error when retrieving current configuration of:
Resource: "/v1, Resource=persistentvolumes", GroupVersionKind: "/v1, Kind=PersistentVolume"
Name: "test/task-pv-volume", Namespace: ""
from server for: "test_pvc.yaml": invalid resource name "test/task-pv-volume": [may not contain '/']
```

I'd suggest trying on newer server version because 1.20 looks too old.

Since this is not a bug, I'm closing this issue. Feel free to re-open it if you think otherwise.

/close
