### ISSUE TITLE
Kubectl convert (pluggin) doesn't correctly handle manifests with multiple kinds

### ISSUE THREAD

**Issue by junkiebev** [kubernetes/kubectl#1383]
**What happened**:
running the command
`kubectl convert -f manifest.yaml --output-version 'networking.k8s.io/v1'`

against a file with this content
```yaml
apiVersion: v1
kind: Service
metadata:
  name: uat-odata
  namespace: uat-front
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: odata
    env: uat
    instance: front
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: uat-ingress
  namespace: uat-front
spec:
  rules:
  - host: uat.company.com
    http:
      paths:
      - backend:
          serviceName: uat-odata
          servicePort: 80
        path: /odata
        pathType: ImplementationSpecific
      - backend:
          serviceName: webapi
          servicePort: 80
        path: /api
        pathType: ImplementationSpecific
```
results in the following output:
`error: core.Service is not suitable for converting to "networking.k8s.io/v1" in scheme "pkg/api/legacyscheme/scheme.go:30"`
**What you expected to happen**:

It's fairly obvious _why_ this is happening - the Service doesn't have an appropriate apiVersion.

I'm curious how one might go about skipping mismatches in a master manifest (think something that kustomize might create).

**Environment**:
- `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14"`
- `v1.26.2` is the pluggin version I'm using
- Cloud provider or hardware configuration: (n/a - it's local)
- OS (e.g: `cat /etc/os-release`): `PRETTY_NAME="Ubuntu 22.04.2 LTS"`
