### ISSUE TITLE
Modifying a paused deployment's maxSurge value does not work as expected

### ISSUE THREAD

**Issue by dudicoco** [kubernetes/kubectl#1390]
### What happened?

While a deployment is paused after a rollout to a new replicaset has started, modifying the `maxSurge` value will result in incorrect scaling of the old replicaset instead of the new one.

### What did you expect to happen?

The new replicaset to be scaled instead of the old one.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a deployment
2. Edit the deployment to change an environment variable within a container
3.Pause the deployment Immediately after new pods are created - `kubectl rollout pause deployment my-deployment`
4. Edit the deployment - increase the `maxSurge` value
5. Watch the old replicaset being scaled out

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by eddiezane** [comment]
We discussed this and determined that it's working as expected.

Imperative commands like `kubectl rollout pause` and `kubectl edit` are going to run into issues when you are fighting against controllers trying to resolve state. The recommended approach here is to use the declarative `kubectl apply` in both scenarios.

/close

**Comment by dudicoco** [comment]
> We discussed this and determined that it's working as expected.
> 
> Imperative commands like `kubectl rollout pause` and `kubectl edit` are going to run into issues when you are fighting against controllers trying to resolve state. The recommended approach here is to use the declarative `kubectl apply` in both scenarios.
> 
> /close

@eddiezane the pause feature itself IS declarative. You can set `paused: true` within the deployment's manifest and apply it in order to pause it.

In addition, there is nothing in the docs stating that commands like `kubectl rollout pause` and `kubectl edit` are going to run into issues when you are fighting against controllers trying to resolve state, if that's the case I would expect it to be a huge red warning in the docs that these commands are not suitable for use in production.

I'm not sure why you were so quick to close this issue without any public discussion, not very suitable to an open source project.

So with these in mind, this still seems to me like a bug that needs to be solved.

/reopen

**Comment by eddiezane** [comment]
> @eddiezane the pause feature itself IS declarative. You can set paused: true within the deployment's manifest and apply it in order to pause it.

Are you able to replicate the issue you are seeing by doing this? If so that's something we should look into.

> In addition, there is nothing in the docs stating that commands like `kubectl rollout pause` and `kubectl edit` are going to run into issues when you are fighting against controllers trying to resolve state, if that's the case I would expect it to be a huge red warning in the docs that these commands are not suitable for use in production.

We have a section [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/#management-techniques) but it could probably be called out better. Happy to take a PR over in [the docs](https://github.com/kubernetes/website/blob/dee7405a87d13ed78d53dac53a9dd122b7fb7e29/content/en/docs/concepts/overview/working-with-objects/object-management.md?plain=1#L17-L20) to make it better. We've also presented about it a few times which might be worth adding as well.

https://youtu.be/eOxy1PS5TyQ?t=780
https://youtu.be/BDZFtYUnmCw?t=491

> I'm not sure why you were so quick to close this issue without any public discussion, not very suitable to an open source project.

Appologies, we're all volunteers and get several hundred issues a week between this and the main Kubernetes repo. We meet monthly to triage these to try and keep up with the demand. You can find the recording where we discussed this [here](https://youtu.be/YtJf3uHlnw0?t=2840) (thanks for the reminder to upload it).

Would love for you to join us in the future - https://github.com/kubernetes/community/blob/master/sig-cli/README.md#meetings

**Comment by dudicoco** [comment]
@eddiezane I've tested this again using declarative `kubectl apply` commands and the issue did not occur, so it is related to imperative commands.

I wonder though, aren't controllers also imperative rather than declarative? For example if I have a controller that pauses a deployment, wouldn't it also perform patches and thus fight against other controllers?

**Comment by dudicoco** [comment]
@eddiezane just tested this again as I've didn't follow the steps correctly, I was able to recreate the issue using declarative commands:

1. apply the following manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  replicas: 10
  paused: false
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
2. apply the manifest with the container port modified:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  replicas: 10
  paused: false
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
```
3. while the deployment is rolling out, apply the paused manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  replicas: 10
  paused: true
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
```
3. get current state:
```sh
$ kubectl get pods -l app=nginx
NAME                     READY   STATUS    RESTARTS   AGE
nginx-64bd7b69c-8pphx    1/1     Running   0          57s
nginx-64bd7b69c-9drcb    1/1     Running   0          56s
nginx-64bd7b69c-9swdj    1/1     Running   0          59s
nginx-64bd7b69c-hlzd2    1/1     Running   0          61s
nginx-66b6c48dd5-4stsn   1/1     Running   0          108s
nginx-66b6c48dd5-4tc5v   1/1     Running   0          108s
nginx-66b6c48dd5-64h6v   1/1     Running   0          108s
nginx-66b6c48dd5-9dgcb   1/1     Running   0          108s
nginx-66b6c48dd5-ddq5q   1/1     Running   0          108s
nginx-66b6c48dd5-fhn2j   1/1     Running   0          108s
nginx-66b6c48dd5-sdccz   1/1     Running   0          108s
```
4. apply the manifest with modified `maxSurge`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 10
  paused: true
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
```
5. both the new and the old replicset are scaled out, we would expect only the new replicaset to be scaled out:
```sh
kubectl get pods -l app=nginx
NAME                     READY   STATUS    RESTARTS   AGE
nginx-64bd7b69c-8pphx    1/1     Running   0          4m26s
nginx-64bd7b69c-9787v    1/1     Running   0          72s
nginx-64bd7b69c-9drcb    1/1     Running   0          4m25s
nginx-64bd7b69c-hlzd2    1/1     Running   0          4m30s
nginx-64bd7b69c-vqp75    1/1     Running   0          27s
nginx-66b6c48dd5-4stsn   1/1     Running   0          5m17s
nginx-66b6c48dd5-4tc5v   1/1     Running   0          5m17s
nginx-66b6c48dd5-64h6v   1/1     Running   0          5m17s
nginx-66b6c48dd5-8rt8n   1/1     Running   0          72s
nginx-66b6c48dd5-9dgcb   1/1     Running   0          5m17s
nginx-66b6c48dd5-b8th5   1/1     Running   0          72s
nginx-66b6c48dd5-ddq5q   1/1     Running   0          5m17s
nginx-66b6c48dd5-fhn2j   1/1     Running   0          5m17s
nginx-66b6c48dd5-lvbdd   1/1     Running   0          27s
nginx-66b6c48dd5-sdccz   1/1     Running   0          5m17s
```
