### ISSUE TITLE
resource-type pv ignore option -n

### ISSUE THREAD

**Issue by fotto1** [kubernetes/kubectl#1413]
**What happened**:

`kubectl get pv -n <my-namespace>`

I get all pv of the kubernetes cluster

**What you expected to happen**:

It shall fail when the option `-n` is used after it seems not supported.

**How to reproduce it (as minimally and precisely as possible)**:

Easily run the mentioned commands above on any cluster.

**Anything else we need to know?**:

Unintentional deletion of more resources then expected by kubernetes administrator.

**☠Don't run this on your machine!☠**
```bash
kubectl get pv -n <my-namespace> -o json | jq -r .items[].metadata.name | xargs kubectl delete pv -n <my-namespace>
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```yaml
clientVersion:
  buildDate: "2022-11-09T13:36:36Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: clean
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: windows/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-01-24T19:17:48Z"
  compiler: gc
  gitCommit: 9176fb99b52f8d5ff73d67fea27f3a638f679f8a
  gitTreeState: clean
  gitVersion: v1.24.10-eks-48e63af
  goVersion: go1.19.5
  major: "1"
  minor: 24+
  platform: linux/amd64
```
- Cloud provider or hardware configuration:
AWS EKS Cluster with Kubernetes Version v1.24.10-eks-48e63af
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
