### ISSUE TITLE
KUBE_EDITOR path with spaces on Windows doesn't work

### ISSUE THREAD

**Issue by theNailz** [kubernetes/kubectl#1422]
**What happened**:
I'm trying to configure kubectl to edit files using Sublime Text 3. My Sublime Text is installed in the default location (`C:\Program files\Sublime Text 3\sublime_text.exe`), which contains spaces.
I cannot seem to find the correct syntax for defining the KUBE_EDITOR environment variable, which works with this path.

**What you expected to happen**:
`kubectl edit <resource>` starts Sublime Text with the given resource yaml.

**How to reproduce it (as minimally and precisely as possible)**:

```powershell
# Define the environment variable through system settings and run `kubetl edit <resource>`, or use this one-linerin Powershell
# See also: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3#using-the-variable-syntax
$Env:KUBE_EDITOR="C:\Program Files\Sublime Text 3\sublime_text.exe" ; kubectl edit svc myservice
```

**Anything else we need to know?**:

I've tried the following values, none of these work:
* `C:\Program Files\Sublime Text 3\sublime_text.exe` (This is the correct path.)
* `"C:\Program Files\Sublime Text 3\sublime_text.exe`"
* `'C:\Program Files\Sublime Text 3\sublime_text.exe'`
* `C:\\Program Files\\Sublime Text 3\\sublime_text.exe`
* `file://C:/Program%20Files/Sublime%20Text%203/sublime_text.exe`

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
PS C:\dev> kubectl version --output=yaml
clientVersion:
  buildDate: "2023-04-14T13:21:19Z"
  compiler: gc
  gitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b
  gitTreeState: clean
  gitVersion: v1.27.1
  goVersion: go1.20.3
  major: "1"
  minor: "27"
  platform: windows/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-04-20T00:33:18Z"
  compiler: gc
  gitCommit: 8d0255af07e95b841952563253d27b0d10bd72f0
  gitTreeState: clean
  gitVersion: v1.26.4+k3s1
  goVersion: go1.19.8
  major: "1"
  minor: "26"
  platform: linux/amd64
```
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`):
```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```
