### ISSUE TITLE
client-side apply applies manifest partially

### ISSUE THREAD

**Issue by the-gigi** [kubernetes/kubectl#1450]
**What happened**:

I used `kubectl apply` to apply a change to a Kyverno policy. Only part of the change was applied.

when I used `kubectl apply --server-side` all the changes were applied

**What you expected to happen**:

I expected client-side kubectl apply to correctly apply all the changes, just like server-side apply does.

**How to reproduce it (as minimally and precisely as possible)**:

You'll need the Kyverno cluster policy CRD. If you have Kyverno installed, it's already installed as part of all the CRDs.

If not, I put just the cluster policy CRD in a gist. You can install it like so:

```
$ kubectl apply -f https://gist.githubusercontent.com/the-gigi/a287130c5ac76d71bde84e39ba709022/raw/4936ab70e9f3874483db6917d5d1bd502861dbba/clusterpolicies.kyverno.io.yaml --server-side

customresourcedefinition.apiextensions.k8s.io/clusterpolicies.kyverno.io serverside-applied
```

Then install the policy:

```
$ echo '
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-pod-anti-affinity
spec:
  validationFailureAction: Enforce
  failurePolicy: Ignore
  rules:
    - name: disallow-pod-anti-affinity
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
      exclude:
        all:
          - resources:
              namespaces:
                - ns-1
                - ns-2
      validate:
        message: >-
          Policy Violation: Workload with pod anti-affinity not allowed by policy.
        pattern:
          spec:
            template:
              spec:
                =(affinity): {}
' | kubectl apply -f -

clusterpolicy.kyverno.io/disallow-pod-anti-affinity created
```

Now, apply the following change using client-side apply. 

```
echo '
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-pod-anti-affinity
spec:
  validationFailureAction: Enforce
  failurePolicy: Ignore
  rules:
    - name: disallow-pod-anti-affinity
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
      exclude:
        all:
          - resources:
              namespaces:
                - ns-3
      validate:
        message: >-
          Policy Violation: Workload with pod anti-affinity not allowed by policy. 
        pattern:
          spec:
            template:
              spec:
                =(affinity):
                  X(podAntiAffinity): null
' | kubectl apply -f -

clusterpolicy.kyverno.io/disallow-pod-anti-affinity configured
```

The expected changes are:

1. the excluded namespaces should be just `ns-3`, instead of `ns-1` and `ns-2`
2. the spec affinity at the bottom should be `X(podAntiAffinity): null` instead of '{}'

However, only the 1st change was actually applied:

```
$ kubectl get clusterpolicies disallow-pod-anti-affinity -o yaml | yq '.spec.rules[0]'
exclude:
  all:
    - resources:
        namespaces:
          - ns-3
match:
  any:
    - resources:
        kinds:
          - Deployment
          - StatefulSet
name: disallow-pod-anti-affinity
validate:
  message: 'Policy Violation: Workload with pod anti-affinity not allowed by policy. '
  pattern:
    spec:
      template:
        spec:
          =(affinity): {}
```

Now, let's repeat the same command except we will use server-side apply

```
echo '
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-pod-anti-affinity
spec:
  validationFailureAction: Enforce
  failurePolicy: Ignore
  rules:
    - name: disallow-pod-anti-affinity
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
      exclude:
        all:
          - resources:
              namespaces:
                - ns-3
      validate:
        message: >-
          Policy Violation: Workload with pod anti-affinity not allowed by policy. 
        pattern:
          spec:
            template:
              spec:
                =(affinity):
                  X(podAntiAffinity): null
' | kubectl apply --server-side --force-conflicts -f -

clusterpolicy.kyverno.io/disallow-pod-anti-affinity serverside-applied
```

Now, all is well including the affinity in the spec

```
$ kubectl get clusterpolicies disallow-pod-anti-affinity -o yaml | yq '.spec.rules[0]'                   kind-trouble | default
exclude:
  all:
    - resources:
        namespaces:
          - ns-3
match:
  any:
    - resources:
        kinds:
          - Deployment
          - StatefulSet
name: disallow-pod-anti-affinity
validate:
  message: 'Policy Violation: Workload with pod anti-affinity not allowed by policy. '
  pattern:
    spec:
      template:
        spec:
          =(affinity):
            X(podAntiAffinity): null
```

**Anything else we need to know?**:

`kubectl patch` works like a charm. This command fixes the issue:

```
kubectl patch clusterpolicy disallow-pod-anti-affinity --type=json -p='[{"op": "replace", "path": "/spec/rules/0/validate/pattern/spec/template/spec/=(affinity)", "value": {"X(podAntiAffinity)": null}}]'
```

And, this command sets it to the original value

```
kubectl patch clusterpolicy disallow-pod-anti-affinity --type=json -p='[{"op": "replace", "path": "/spec/rules/0/validate/pattern/spec/template/spec/=(affinity)", "value": {}}]'
```
In addition, I ran the client-side apply with verbose logging, which shows the request body that kubectl uses and indeed it is missing the 2nd change to the affinity. Here is the relevant snippet from the output

```
"spec":{"rules":[{"exclude":{"all":[{"resources":{"namespaces":["ns-3"]}}]},"match":{"any":[{"resources":{"kinds":["Deployment","StatefulSet"]}}]},"name":"disallow-pod-anti-affinity","validate":{"message":"Policy Violation: Workload with pod anti-affinity not allowed by policy. ","pattern":{"spec":{"template":{"spec":{"=(affinity)":{}}}}}}}]}}
I0714 21:44:19.239019   90445 round_trippers.go:466] curl -v -XPATCH  -H "User-Agent: kubectl1.25.2/v1.25.2 (darwin/amd64) kubernetes/5835544" -H "Accept: application/json" -H "Content-Type: application/merge-patch+json" 'https://127.0.0.1:54057/apis/kyverno.io/v1/clusterpolicies/disallow-pod-anti-affinity?fieldManager=kubectl-client-side-apply&fieldValidation=Strict'
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.6
```

- Cloud provider or hardware configuration:

MacBook Pro M1 Max

- OS (e.g: `cat /etc/os-release`):
macOS Venture
