### ISSUE TITLE
Kubectl explain show "example" section for CRD fields

### ISSUE THREAD

**Issue by bbkgh** [kubernetes/kubectl#1468]
Hello all. 
How can users view examples for a field in CRD? `kubectl explain CRD.FIELD` doesn't show example section. for example:
```
....
              gitBranchName:
                default: main
                description: Git branch name that will be used for building your app.
                example: main
                type: string
```
`kubectl explain crdName.spec.gitBranchName `  results to:

```
...

FIELD:    gitBranchName <string>
DESCRIPTION:
     Git branch name that will be used for building your app.
```
It's useful for users to see examples of field in explain command.
