### ISSUE TITLE
kubectl events doesn't filter events by group and version for resource with full name

### ISSUE THREAD

**Issue by scuzhanglei** [kubernetes/kubectl#1470]
**What happened**:

for kubectl v1.28, if there are two resource with same `Kind`, `version` and `name` but different `Group`(eg: `Resource.v1.goup1/name` and `Resource.v1.group2/name`)

`kubectl events --for Resource1.v1.group1/name` will get events  for both two resource.

**What you expected to happen**:

`kubectl events --for` only get events for the exactly resource

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

related PR: https://github.com/kubernetes/kubernetes/pull/117034

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):

```
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by Ithrael** [comment]
Hello, I'm not sure if you made a typo when using "Resource1" in the command "kubectl events --for Resource1.v1.group1/name". Did you mean to write "Resource" instead？
Kubernetes can simultaneously have resources with the same Kind, version, and name but different API Group.

I have performed a test and created two CRDs.
<img width="759" alt="image" src="https://github.com/kubernetes/kubectl/assets/38208715/77fa22ee-bd39-48f7-b945-97768087edc8">
ct1.yml
```
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: ct
spec:
  cronSpec: "* * * * *"
  image: test
```
ct2.yml
```
apiVersion: "test.example.com/v1"
kind: CronTab
metadata:
  name: ct
spec:
  cronSpec: "* * * * *"
  image: test
```
<img width="434" alt="image" src="https://github.com/kubernetes/kubectl/assets/38208715/0d4fd98f-92d5-462e-a56b-05d023b83ef3">

<img width="531" alt="image" src="https://github.com/kubernetes/kubectl/assets/38208715/b17d9b23-2d28-41b7-bcff-51bec96a0ad3">
