### ISSUE TITLE
The command `autoscale deployment` should provide a flag for providing the maximum, average memory utilization

### ISSUE THREAD

**Issue by bmuschko** [kubernetes/kubectl#1481]
**What would you like to be added**:

At this time, an end user can only provide the maximum, average CPU utilization using the `--cpu-percent`. The API version `autoscaling/v2` allows for define a memory resource metric for memory as well. The ask is to introduce a flag for this metric, e.g. `--memory-value`. For example, the `--memory-value=500Mi` would generate the following manifest representation:

```
spec:
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi
```

**Why is this needed**:

Align the imperative capabilities for creating a Horizontal Pod Autoscaler with the declarative capabilities. As a user, I am somewhat confused why I don't have the option to provide memory thresholds.

**Comment by brianpursley** [comment]
Since you can do this using yaml and kubectl apply, we'd like to hold off on adding any new flags for particular settings.

A kubectl plugin might be be a good place to start, if you want to implement this, and if it is something generally helpful as a plugin, then we can see about implementing it in kubectl.

**Comment by bmuschko** [comment]
Thanks for the info! Sounds good to me. Maybe it would be good idea to deprecate the `autoscale` command completely and force users into the declarative approach.

**Comment by brianpursley** [comment]
> Thanks for the info! Sounds good to me. Maybe it would be good idea to deprecate the `autoscale` command completely and force users into the declarative approach.

You make a good point though.  Something like autoscale is a pretty niche command, and if it doesn't support enough use cases, should it even exist as a command and be deprecated instead?

In the past, we have seen commands like `kubectl run` explode with a large number of flags, making it difficult to maintain and ultimately difficult for users to understand and use effectively.  It also causes problems when you consider version skew because some flags may refer to functionality that is either too old or too new for the server you are talking to, again adding complexity.  So for these reasons, our go-to answer has been to use `kubectl apply` as much as possible.

For something like this command though, perhaps the reasoning would be different, since it has a very particular use.  I can add it to the agenda for the next sig-cli meeting for group discussion.

**Comment by brianpursley** [comment]
@bmuschko We talked about it at the meeting today, and decided this would be a useful flag to add.  

As I mentioned before, our "default" answer for new flags is no, in order to avoid adding too many flags, but in this case, being able to autoscale based on memory is consistent with the type of functionality already provided by `--cpu-percent`, so it makes sense for this new flag to be added.

I'm not too familiar with HPA, but it looks like it supports both "value" and "percent" for both CPU and memory.

Do you need to scale based on the memory value or percent?  I'm thinking for consistency, the new flag should be `--memory-percent`, since the command currently operates on CPU percent.

Do you need to be able to scale based on memory value?  If so, then I'm guessing that would mean adding a `--memory` flag and then also a `--cpu` flag (to keep them consistent)  :sweat_smile:

**Comment by bmuschko** [comment]
Looking at the [API documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#metrictarget-v2-autoscaling), you can have the following permutations.

**Average utilization in percentage (cpu or memory):**

```
type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
```

**Average utilization as fixed-point representation of a number (cpu or memory):**

```
type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 1.5
```

**Value as fixed-point representation of a number (cpu or memory):**

```
type: Resource
    resource:
      name: cpu
      target:
        type: Value
        value: 1
```

If you wanted to cover all options by CLI flag, you'd have to introduce 6 of them overall. You'd probably also want to rename (plus deprecate) the existing one e.g. from `--cpu-percent` to `--cpu-utilization-percent`.

```
--cpu-percent
--memory-percent
--cpu-average-value
--memory-average-value
--cpu-value
--memory-value
```

You think it would be worth it maintaining all of those flags? After thinking this through, I still think it may be better to deprecate the `autoscale` command altogether.
