### ISSUE TITLE
False success creating secret for type kubernetes.io/service-account-token when service account does not exist

### ISSUE THREAD

**Issue by newtondev** [kubernetes/kubectl#1496]
**What happened**:

I created a Kubernetes `secret` with type of `kubernetes.io/service-account-token` for a service account that did not exist. The response from executing the `kubectl apply -f secret.yaml` command resulting in a message indicating the secret was successfully created. When trying to retrieve the secret it does not exist.

I soon realized that the service account was not initially created due to ordering issue in our IaC script. When applying both the service account and secret then both resources are created and visible on the cluster.

My problem with this is that the false "created successfully" message when creating the secret is not correct as the secret does not exist after the creation was executed.

**What you expected to happen**:

An error exit code and a message indicating the service account does not exist.

**How to reproduce it (as minimally and precisely as possible)**:

Create a file `secret.yaml` with the following contents:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-nonexistent-sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: test-nonexistent-sa
type: kubernetes.io/service-account-token
```

Apply it to your cluster: `kubectl apply -f secret.yaml`

The response indicates the secret creation was successful.

Check your secrets: `kubectl get secret -n default`

![image](https://github.com/kubernetes/kubectl/assets/2195600/5b5c7def-26ff-4523-b0d0-cc4d25762ce4)

The secret is nowhere to be found. This is a problem as I use the exit code of the `kubectl get secret ...` in a script to determine if something was not applied to the cluster.

However if you create the service account first and then create the secret, then this all works.

Create a file `sa_with_secret.yaml`:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-nonexistent-sa
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: test-nonexistent-sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: test-nonexistent-sa
type: kubernetes.io/service-account-token
```

Apply it to your cluster: `kubectl apply -f sa_with_secret.yaml`

Check for the sa and the secret: `kubectl get sa,secret -n default`

<img width="593" alt="image" src="https://github.com/kubernetes/kubectl/assets/2195600/c8221574-b221-4a38-a792-da4f1cd53855">

Both the service account and secret then exist.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/amd64"} -- Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-09-01T23:34:08Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/arm64"}
- Cloud provider or hardware configuration: kind v0.19.0 go1.20.6 darwin/arm64 running Kubernetes v1.25.0 control-plane
- OS (e.g: `cat /etc/os-release`): macOS 13.5.2
