### ISSUE TITLE
Issues in Pull local image irrespective of ` imagePullPolicy: Never` tag

### ISSUE THREAD

**Issue by veris-neerajdhiman** [kubernetes/kubectl#15]
- I am trying to create a pod from local docker image which I have created . 

![selection_006](https://cloud.githubusercontent.com/assets/15321333/26352052/b2c74612-3fd7-11e7-8c9d-ffdcbf62fd97.png)

- Below is my yaml file 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: dockertest-web-1
      image: nd/djclone
      ports:
      - containerPort: 8000
      imagePullPolicy: Never
```
- Command : 
![selection_007](https://cloud.githubusercontent.com/assets/15321333/26352167/38202aea-3fd8-11e7-8651-939997926878.png)

- Dashboard view : 
![kubernetes dashboard](https://cloud.githubusercontent.com/assets/15321333/26352210/5fa8182a-3fd8-11e7-87ce-3490208b79ba.png)
