### ISSUE TITLE
Unable to issue --enable-helm to kubectl delete command

### ISSUE THREAD

**Issue by djryanj** [kubernetes/kubectl#1509]
**What happened**:

Trying to `kubectl delete -k <dir> --enable-helm` results in kubectl reporting: `error: unknown flag: --enable-helm`. Removing `--enable-helm` results in

```
error: trouble configuring builtin HelmChartInflationGenerator with config: <config>: must specify --enable-helm
```

**What you expected to happen**:

`delete` should work the same as `apply`.

**How to reproduce it (as minimally and precisely as possible)**:

Create a basic kustomize overlay that references some helm chart, e.g.:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd-viz

resources:
  - ../base

helmCharts:
- name: linkerd-viz
  repo: https://helm.linkerd.io/stable
  version: 30.12.2
  releaseName: linkerd-viz
  namespace: linkerd-viz
  valuesFile: values.yaml
```

Apply with `kubectl apply -k <config dir> --enable-helm`

Wait for it to apply

Try to delete it with `kubectl delete-k <config dir> --enable-helm`

Observe

**Anything else we need to know?**:

N/A
**Environment**:

- Kubernetes client and server versions (use `kubectl version`):
  - Client Version: v1.27.3
  - Kustomize Version: v5.0.1
  - Server Version: v1.27.6+k3s1
- Cloud provider or hardware configuration:
  - Azure IaaS VMs for server, Windows 11 desktop for client 
- OS (e.g: `cat /etc/os-release`):
