### ISSUE TITLE
Updating with Non Existing Resource Name Gets Success Response

### ISSUE THREAD

**Issue by haseungyeon** [kubernetes/kubectl#1527]
**What happened**: I updated rbac.authorization.k8s.io/v1 role binding for non-existent resources using the python kubernetes-asyncio library, but I get a 200 normal response and create a new resource. It is said that the same result occurred when running with kubectl, and the same bug occurs when runtime class and limit range update.
https://github.com/tomplus/kubernetes_asyncio/issues/294

**What you expected to happen**: I think 404 not found error should occur when updating for all nonexistent role binding, runtime class, and limit range.

**How to reproduce it (as minimally and precisely as possible)**: 
```yaml
# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: non-existing-resource
  namespace: default
subjects:
- kind: User
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```
```bash
kubectl replace -f role-binding.yaml
```
```yaml
# runtime-class.yaml
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: non-existing-resource
handler: myconfiguration
```
```bash
kubectl replace -f runtime-class.yaml
```
```yaml
# limit-range.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: non-existing-resource
spec:
  limits:
  - type: Container
    default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 250m
    max:
      memory: 1024Mi
      cpu: 1000m
    min:
      memory: 128Mi
      cpu: 125m
    maxLimitRequestRatio:
      memory: 2
      cpu: 2
```
```bash
kubectl replace -f limit-range.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 
```pre
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:48:26Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:42:11Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: vmware-vsphere 7.0.3.00700
- OS (e.g: `cat /etc/os-release`): 
```pre
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
