### ISSUE TITLE
kubectl diff command output diff informations when patch is failed for statefulset

### ISSUE THREAD

**Issue by zhangzhiqiangcs** [kubernetes/kubectl#1531]
### What would you like to be added?

when statefulset patch is failed, kubectl output the the patch informations, not just output something like
```
updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy' and 'minReadySeconds' are forbidden
```

### Why is this needed?

some  patch information may help user to understand why patch is failed, it is useful when the actual diff is not so obvious

**Comment by Ithrael** [comment]
Could you please explain the steps you took to reproduce this?

**Comment by zhangzhiqiangcs** [comment]
@Ithrael Hi, here is the example sts, I just change the labels on the `volumeClaimTemplates`. Apply a1.yaml, and then use `kubectl diff -f a1.yaml`
a1.yaml
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```
a2.yaml
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      labels:
        app: myapp
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```
