### ISSUE TITLE
kubectl: Unclear TARGETS (CPU or Memory) in the output of `kubectl get hpa`

### ISSUE THREAD

**Issue by able8** [kubernetes/kubectl#1540]
### What happened?

After running `kubectl get hpa`, the result show `105%/75%, 10%/75%` in the `TARGETS` list.
But whether the order is `cpu, memory` or  `memory, cpu` is unclear.
It would be clearer if it could show `memory 105%/75%, cpu 10%/75%`.

```
➜  ~ kubectl get hpa
NAME                              REFERENCE                                    TARGETS             MINPODS   MAXPODS   REPLICAS   AGE
ingress-nginx-controller          Deployment/ingress-nginx-controller          105%/75%, 10%/75%   3         11        11       
```

### What did you expect to happen?

Displaying "memory 105%/75%, cpu 10%/75%" ?

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an HPA with CPU and Memory metrics 
2. Run `kubectl get hpa`

```
spec:
  maxReplicas: 11
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
....
```

### Kubernetes version

v1.25.10

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
