### ISSUE TITLE
Unable to use https proxy with kubectl

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubectl#1558]
**What happened**: I am trying to use https proxy against our cluster with kubectl config

```
- cluster:
    insecure-skip-tls-verify: true
    proxy-url: https://kubectl-proxy.company.com
    server: https://[snip].elb.eu-central-1.amazonaws.com
  name: [snip]
```

```
% kubectl get nodes
Get "https://[snip].elb.eu-central-1.amazonaws.com/api/v1/nodes?limit=500": malformed HTTP response "\x00\x00\x1e\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x01\x00\x00\x10\x00\x00\x04\x00\x10\x00\x00" - error from a previous attempt: unexpected EOF
```

If I use http://kubectl-proxy.company.com as proxy everything works fine. 

**What you expected to happen**:

I expect that I could use https proxy.

1) our https proxy do have valid tls certificate which works if system cert pool is loaded
2) our kubernetes api is using custom ca

Example how it is possible to make this installation working with raw golang http.Transport:

```
	caCertPool, err := x509.SystemCertPool()
	if err != nil {
		return err
	}
	caCertPool.AppendCertsFromPEM([]byte(ca)) <--- ca contains information for kubernetes api
	tlsConfig := &tls.Config{
		RootCAs:    caCertPool,
		MinVersion: tls.VersionTLS12,
	}

	tp := &http.Transport{TLSClientConfig: tlsConfig}

	proxyUrl, err := url.Parse("https://kubectl-proxy.company.com")
	if err != nil {
		return fmt.Errorf("error parsing proxy url: %w", err)
	}
	tp.Proxy = http.ProxyURL(proxyUrl)
```

When using https proxy with custom CA kubernetes api, we need possibility to define 2 different CAs (or cert pool). Currently it looks like its not possible with kubectl. It seems that its not possible to get https proxy currently working even with overriding `insecure-skip-tls-verify: true` 

**How to reproduce it (as minimally and precisely as possible)**:

1) install kubernetes cluster with custom CA (like kOps)
2) try to connect to it through https proxy which have valid certificate.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): both 1.29.1
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): mac

**Comment by eddiezane** [comment]
Hey @zetaab! It's a bit unclear the need you're describing for 2 different CA's. From your example I *think* you're missing the cluster's CA that's standard for a kubeconfig?

```
- cluster:
    insecure-skip-tls-verify: true
    proxy-url: https://kubectl-proxy.company.com
    server: https://[snip].elb.eu-central-1.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTi......
  name: [snip]
```

Please reopen if this is something else.

/close
