### ISSUE TITLE
`kubectl diff` and `kubectl apply --dry-run=server` fail when simultaneously creating `Role` and `RoleBinding`

### ISSUE THREAD

**Issue by armingerten** [kubernetes/kubectl#1575]
**What happened**:
When running `kubectl diff` or `kubectl apply` with the `--dry-run=server` option on a manifest file containing both `Role` and `RoleBinding`, one will receive a `NotFound` error message:

Error message for `apply --dry-run=server`:
```sh
Error from server (NotFound): error when creating "manifests.yml": roles.rbac.authorization.k8s.io "pod-reader" not found
```
Error message for `diff`:
```sh
Error from server (NotFound): roles.rbac.authorization.k8s.io "pod-reader" not found
```

Applying the resources with `kubectl apply -f manifests.yml` however works successfully as long as `RoleBinding` manifests appear after `Role` manifests within the manifest file.

**What you expected to happen**:
The behavior between `apply`, `apply --dry-run=server` and `diff` must be consistent. 
It should be possible to apply, dry-run or diff manifest files containing roles and rolebinding that are being / would be created in the process.

**How to reproduce it (as minimally and precisely as possible)**:
Run one of the following commands:
- `kubectl apply -f manifests.yml -n my-namespace --dry-run=server`
- `kubectl diff -f manifests.yml -n my-namespace`

on `manifests.yml` with the following content:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: ['']
  resources: ['pods']
  verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: test-serviceaccount
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes server version: `v1.27.7`
- Kubernetes client versions: I tested with: `v1.27.7`, `v1.27.12`, `v1.28.8` and `v1.29.3`
