### ISSUE TITLE
`kubectl describe node` sometimes shows total memory in millibytes

### ISSUE THREAD

**Issue by clux** [kubernetes/kubectl#1597]
via `kubectl describe node XXX`:

<img width="660" alt="Screenshot 2024-05-08 at 14 02 49" src="https://github.com/kubernetes/kubectl/assets/134092/532f82ac-cb6a-4da8-a021-62010f18c74b">

It doesn't always do it. Sometimes requests is correct, but I seem to hit it reasonably frequently. Not sure if this is a size issue or just a place where we do not abbreviate to not lose significant digits?

**Environment**:
EKS 1.29, kubectl client at 1.30.0

**Comment by clux** [comment]
Did some digging and I can indeed find one pod whose req/limits for cpu/mem respectively in the same column shows:
```
ns  one-pod-xxxx            151m (0%)     4500m (28%)  195454566400m (0%)
```

and searching through deployments I did find this request for memory 🙃 

```yaml
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 1m
            memory: 107374182400m
```

so in short, possibly my fault. not sure how this got there.

on the other hand, it's reasonable to want a human readable number in a human readable page?

**Comment by clux** [comment]
oh, wait, i see now, in my root yaml it says:

```yaml
          requests:
            cpu: 1m
            memory: 0.1Gi
```

which means 0.1Gi of memory gets converted to millibytes because it's not perfectly roundable; 
```js
> 0.1*1024*1024*1024*1000
107374182400
```

and this rounding based sub-byte number is then probably propagating through internal calculations 🙃 

so this does not feel like a huge user error (0.1Gi feels like a reasonable way to represent memory), but it leads to hard to read `kubectl describe` output. maybe `kubectl describe` should give you Megabytes as a smallest default for memory, perhaps?

**Comment by brianpursley** [comment]
I see the same thing, and also get a warning.  Here is what I did:
```
$ kubectl apply -f - << EOF
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
  - image: registry.k8s.io/pause 
    name: pause
    resources:
      requests:
        cpu: 1m
        memory: 0.1Gi
EOF
```
```
Warning: spec.containers[0].resources.requests[memory]: fractional byte value "107374182400m" is invalid, must be an integer
pod/foo created
```
```
$ kubectl get pod foo -o json | jq .spec.containers[0].resources
```
```
{
  "requests": {
    "cpu": "1m",
    "memory": "107374182400m"
  }
}
```

Are you able to use `G` instead of `Gi`?
```
kubectl apply -f - << EOF
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
  - image: registry.k8s.io/pause 
    name: pause
    resources:
      requests:
        cpu: 1m
        memory: 0.1G
EOF
```
```
pod/foo created
```
```
$ kubectl get pod foo -o json | jq .spec.containers[0].resources
```
```
{
  "requests": {
    "cpu": "1m",
    "memory": "100M"
  }
}
```
