### ISSUE TITLE
CrashLoopBackOff while creating Pod

### ISSUE THREAD

**Issue by veris-neerajdhiman** [kubernetes/kubectl#16]
- I am getting below error while creating a pod : 
![kubernetes dashboard 1](https://cloud.githubusercontent.com/assets/15321333/26358534/7cf46bdc-3ff0-11e7-8bac-f6df9453052d.png)

- yaml file : 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: docker-io-image
spec:
  containers:
    - name: dockertest-web-1
      image: inforian/dockertest_web
      ports:
      - containerPort: 8000
```

- kubectl config : 

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-05-09T23:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```
