### ISSUE TITLE
Multiline string literals containing three dashes (`---`) can cause YAML parser to fail

### ISSUE THREAD

**Issue by FeldrinH** [kubernetes/kubectl#1645]
**What happened**:

I have a manifest that contains a multiline string literal similar to this:
```yaml
# test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: test:latest
    env:
    - name: PARSE_ERROR_DEMO
      value: "Hello

---multiline"
```

I tried to apply it using `kubectl apply` and got an unexpected error:

```
$ kubectl apply -f test.yaml
error: error parsing test.yaml: invalid Yaml document separator: multiline
```

**What you expected to happen**:

Running `kubectl apply -f test.yaml` the parser should accept this and apply my manifest.

**How to reproduce it (as minimally and precisely as possible)**:

Copy the manifest above to test.yaml and run `kubectl apply -f test.yaml`.

**Anything else we need to know?**:

The problem appears to be caused by the three dashes (`---`) in the string literal. Removing them or adding a different character between the dashes gets rid of the error.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): Client Version: v1.31.0, Server Version: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Windows 10
