### ISSUE TITLE
kubectl debug: profile "sysadmin" does not work as expected when uid != 0 is specified

### ISSUE THREAD

**Issue by Phil1602** [kubernetes/kubectl#1650]
**What happened**:
I wanted to create an ephemeral container with `sysadmin` (or `netadmin`) profile to be able to capture traffic using `tcpdump` using the following command:

```
kubectl debug test-pod -it --image nicolaka/netshoot --profile=sysadmin -- zsh

Defaulting debug container name to debugger-wj6qq.
If you don't see a command prompt, try pressing enter.

test-pod% whoami
whoami: unknown uid 1000

test-pod% tcpdump
tcpdump: eth0: You don't have permission to perform this capture on that device
(socket: Operation not permitted)
```

The ephemeral container is set to `privileged: true` as expected, but the Pod level `securityContext` forces the ephemeral container to run as user `1000` which is IMO an unwanted behavior for an ephemeral container with `sysadmin` profile set.

**What you expected to happen**:
I would expect my ephemeral container with `sysadmin` to be able to capture traffic in any case.

On a container level `securityContext` I would not only expect `privileged: true`, but also `runAsUser: 0` to avoid such user override collisions from pod level. Otherwise: a parameter to override the user for the ephemeral container would help in that regard as well.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Pod with the following securityContext

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod
  name: test-pod
spec:
  securityContext:
    runAsUser: 1000 # Override user != 0
  containers:
  - image: kennethreitz/httpbin
    name: test-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

```

2. Attach ephemeral Container via debug command and profile `sysadmin` set

```
kubectl debug test-pod -it --image nicolaka/netshoot --profile=sysadmin -- zsh

Defaulting debug container name to debugger-wj6qq.
If you don't see a command prompt, try pressing enter.

test-pod% whoami
whoami: unknown uid 1000

test-pod% tcpdump
tcpdump: eth0: You don't have permission to perform this capture on that device
(socket: Operation not permitted)
test-pod% 
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```sh
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3-eks-a18cd3a
```
- Cloud provider or hardware configuration: AWS EKS (see above)

**Comment by ardaguclu** [comment]
@mochizuki875 what do you think about this?.

**Comment by mochizuki875** [comment]
@ardaguclu 
I think the same situation is happening here with ephemeral container.

When `privileged: true` is set for a container running as root user, the following [CapabilitySet](https://man7.org/linux/man-pages/man7/capabilities.7.html) is applied.
The key point is that the `CapEff` where the capabilities actually used for permission checks are set.

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: privileged
  name: privileged
spec:
  containers:
  - image: busybox
    command: ["sh", "-c", "sleep infinity"]
    name: privileged
    securityContext:
      privileged: true
  terminationGracePeriodSeconds: 0
```

```bash
$ kubectl exec -it privileged -- /bin/sh
/ # whoami
root
/ # grep Cap /proc/1/status
CapInh:	0000000000000000
CapPrm:	000001ffffffffff
CapEff:	000001ffffffffff
CapBnd:	000001ffffffffff
CapAmb:	0000000000000000
```

On the other hand, when non-root user is specified in `runAsUser`, even if `privileged: true` or specific capabilities are set, the container process does not have the appropriate capability(`CapEff`), and it can not have the required permission.

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: runasuser-with-privileged
  name: runasuser-with-privileged
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - image: busybox
    command: ["sh", "-c", "sleep infinity"]
    name: runasuser-with-privileged
    securityContext:
      privileged: true
  terminationGracePeriodSeconds: 0
```

```bash
$ kubectl exec -it runasuser-with-privileged -- /bin/sh
~ $ whoami
whoami: unknown uid 1000
~ $ grep Cap /proc/1/status
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	000001ffffffffff
CapAmb:	0000000000000000
```

I have not checked the details yet, but this issue has been reported in [#56374](https://github.com/kubernetes/kubernetes/issues/56374), and [KEP #2763](https://github.com/kubernetes/enhancements/issues/2763) has been proposed.
However, it seems to not be implemented yet.


So currently, I think the simplest workaround is to define `runAsUser` under the `containers` field.

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod
  name: test-pod
spec:
  # securityContext:
  #   runAsUser: 1000 # Override user != 0
  containers:
  - image: kennethreitz/httpbin
    name: test-pod
    securityContext:
      runAsUser: 1000 # Override user != 0
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
```

```bash
$ kubectl debug test-pod -it --image nicolaka/netshoot --profile=sysadmin -- zsh
Defaulting debug container name to debugger-dwt84.
If you don't see a command prompt, try pressing enter.
test-pod  ~  whoami
root
test-pod  ~  grep Cap /proc/$$/status
CapInh:	0000000000000000
CapPrm:	000001ffffffffff
CapEff:	000001ffffffffff
CapBnd:	000001ffffffffff
CapAmb:	0000000000000000
```

or using [Custom Profile](https://kubernetes.io/blog/2024/08/22/kubernetes-1-31-custom-profiling-kubectl-debug/).

`profile-runas-root.yaml`
```yaml
securityContext:
  runAsUser: 0
  privileged: true
```

```bash
$ kubectl get pod test-pod -o=jsonpath={.spec.ephemeralContainers[0].securityContext} | jq .
zsh: no matches found: -o=jsonpath={.spec.ephemeralContainers[0].securityContext}

$ kubectl debug test-pod -it --image=busybox --custom=profile-runas-root.yaml -- /bin/sh
Defaulting debug container name to debugger-mjp6g.
If you don't see a command prompt, try pressing enter.
/ # grep Cap /proc/$$/status
CapInh:	0000000000000000
CapPrm:	000001ffffffffff
CapEff:	000001ffffffffff
CapBnd:	000001ffffffffff
CapAmb:	0000000000000000
```


Another solution which I come up with is to set `runAsUser: 0` to ephemeral container when `--profile=sysadmin` or `--profile=netadmin` is specified.
However, I don't know it's appropriate...
