### ISSUE TITLE
kubectl diff should have an option to use `kubectl replace` instead of `kubectl apply` to generate the diff

### ISSUE THREAD

**Issue by frankh** [kubernetes/kubectl#1686]
**What would you like to be added**:
A `--replace` flag or similar to make `kubectl diff` use `kubectl replace` over `kubectl apply`

**Why is this needed**:
currently there is no way to see fields that have been removed from a desired manifest in `kubectl diff`

for example, with live manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  template:
    spec:
      containers:
      - name: example-container
        image: example-image
        env:
        - name: THING
           value: blah
```

and desired.yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  template:
    spec:
      containers:
      - name: example-container
        image: example-image
```

`kubectl diff -f desired.yaml` will result in no diff

with `--replace` it would correctly show:
```
-        env:
-        - name: THING
-          value: blah
```
