### ISSUE TITLE
`kubectl describe pod` shows strange info in volumes.projected-volumes.SecretOptionalName

### ISSUE THREAD

**Issue by gshaibi** [kubernetes/kubectl#1694]
**What happened**:
When running `kubectl describe pod` on a pod with an optional secret volume I get the following `Volumes` section:
```
Volumes:
  projected-volume:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          secret3
    SecretOptionalName:  0x14000123977
```
The SecretOptionalName is irrelevant and probably be used to show whether the Secret above it is optional or not (boolean).

**What you expected to happen**:
Show boolean optional information regarding the above secret.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: projected-volume
      mountPath: /etc/projected-volume
  volumes:
  - name: projected-volume
    projected:
      sources:
      - secret:
          name: secret3
          optional: true
```

Then, run `kubectl describe pod test-pod` and inspect the Volumes section.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): Client Version: v1.31.3, Kustomize Version: v5.4.2, Server Version: v1.27.3
- Cloud provider or hardware configuration: kind
- OS (e.g: `cat /etc/os-release`):  macOS 15.1 (24B83)
