### ISSUE TITLE
Used ephemeral storage within kubectl top pod command

### ISSUE THREAD

**Issue by 3deep5me** [kubernetes/kubectl#1696]
**What would you like to be added**:
It would be great to get also the current ephemeral storage usage with `kubectl top pods` command.

**Why is this needed**:
This would give useres/me the option to quickly get an estimate for setting [requests-and-limits-for-local-ephemeral-storage](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage) .

**Comment by Ritikaa96** [comment]
This is a good addition for those who has use case. I'd like to work on it if it the triage is accpeted.

**Comment by Ritikaa96** [comment]
@mpuckett159 can confirm this is something that we can add in the code.

**Comment by 3deep5me** [comment]
I would help with the documentation.

**Comment by Ritikaa96** [comment]
sure, Let's first wait for the opinion on accepting the triage.

**Comment by googs1025** [comment]
I'm not sure if I understand it correctly, but does kubectl top pods fetch usage metrics for ephemeral storage? I tried it and it doesn't seem to.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: example-pod-with-ephemeral-storage
spec:
  containers:
  - name: example-container
    image: nginx
    resources:
      requests:
        ephemeral-storage: "500Mi"  
      limits:
        ephemeral-storage: "1Gi"    
    volumeMounts:
    - name: ephemeral-storage-volume
      mountPath: /tmp               
  volumes:
  - name: ephemeral-storage-volume
    emptyDir: {}                   

```

```yaml
root@VM-0-3-ubuntu:/home/ubuntu# curl localhost:8181/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/example-pod-with-ephemeral-storage
{
  "kind": "PodMetrics",
  "apiVersion": "metrics.k8s.io/v1beta1",
  "metadata": {
    "name": "example-pod-with-ephemeral-storage",
    "namespace": "default",
    "creationTimestamp": "2025-01-09T13:46:04Z"
  },
  "timestamp": "2025-01-09T13:45:39Z",
  "window": "17.913s",
  "containers": [
    {
      "name": "example-container",
      "usage": {
        "cpu": "0",
        "memory": "4620Ki"
      }
    }
  ]
}root@VM-0-3-ubuntu:/home/ubuntu# kubectl top pods
NAME                                 CPU(cores)   MEMORY(bytes)
example-pod-with-ephemeral-storage   0m           4Mi
root@VM-0-3-ubuntu:/home/ubuntu# kubectl top pods
NAME                                 CPU(cores)   MEMORY(bytes)
example-pod-with-ephemeral-storage   0m           4Mi
```
