### ISSUE TITLE
NetworkPolicy describer isn't useful

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubectl#17]
"kubectl describe" isn't useful for NetworkPolicies. @thockin says so!

**Comment by aanm** [comment]
If no one is going for this, I can take a stab at this one.

**Comment by adohe** [comment]
@aanm that would be great, and I think I now ready for help review this.

**Comment by aanm** [comment]
@adohe I've made some drafts of the output. Which one do you think looks better?
policy:
```
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: access-backend
spec:
  podSelector:
    matchLabels:
      id: app1
      id2: app3
    matchExpressions:
    - key: foo
      operator: In
      values:
        - bar1
        - bar2
    - key: foo2
      operator: NotIn
      values:
        - bar1
        - bar2
  ingress:
  - from:
    - podSelector:
        matchLabels:
          id: app2
          id2: app3
    - namespaceSelector:
        matchLabels:
          id: app2
          id2: app3
    - namespaceSelector:
        matchLabels:
          id: app2
          id2: app3
        matchExpressions:
        - key: foo
          operator: In
          values:
            - bar1
            - bar2
    ports:
    - port: 80
      protocol: TCP
    - port: 82
  - from:
    ports:
```

Output A
```
Name:           access-backend
Namespace:      default
Created on:     2017-06-02 10:10:58 -0700 PDT
Labels:         <none>
Annotations:    <none>
Spec:
  Pod Selector:
    foo in (bar1,bar2),foo2 notin (bar1,bar2),id=app1,id2=app3
  Allowing ingress traffic:
    From:
      Pod Selector:
        id=app2,id2=app3
      Namespace Selector:
        id=app2,id2=app3
      Namespace Selector:
        foo in (bar1,bar2),id=app2,id2=app3
    To Ports:
      80/TCP
      82/TCP
    ----------
    From:
      <none> (traffic not restricted by source)
    To Ports:
      <none> (traffic allowed to all ports)
```

Output B
```
Name:           access-backend
Namespace:      default
Created on:     2017-06-02 09:33:18 -0700 PDT
Labels:         <none>
Annotations:    <none>
Spec:
  Pod Selector:
    Labels:     id=app1
                id2=app3
    Expre.:     "foo" In [bar1 bar2]
                "foo2" NotIn [bar1 bar2]
  Allowing ingress traffic:
    From:
      Pod Selector:
        Labels: id=app2
                id2=app3
      Namespace Selector:
        Labels: id=app2
                id2=app3
      Namespace Selector:
        Labels: id=app2
                id2=app3
        Expre.: "foo" In [bar1 bar2]
    To Ports:
      80/TCP
      82/TCP
    ----------
    From:
      <none> (traffic not restricted by source)
    To Ports:
      <none> (traffic allowed to all ports)
```
Output C
```
Name:           access-backend
Namespace:      default
Created on:     2017-06-02 10:10:58 -0700 PDT
Labels:         <none>
Annotations:    <none>
Spec:
  Pod Selector:     foo in (bar1,bar2),foo2 notin (bar1,bar2),id=app1,id2=app3
  Allowing ingress traffic:
    From:
      Pod Selector: id=app2,id2=app3
      Namespace Selector: id=app2,id2=app3
      Namespace Selector: foo in (bar1,bar2),id=app2,id2=app3
    To Ports:
      80/TCP
      82/TCP
    ----------
    From:
      <none> (traffic not restricted by source)
    To Ports:
      <none> (traffic allowed to all ports)
```
