### ISSUE TITLE
Add optional kubectl path to kubeconfig

### ISSUE THREAD

**Issue by amaddio** [kubernetes/kubectl#1703]
## Problem
When managing different clusters with different kubectl (server) versions (kubelet api) one has to manually switch between the locally kubectl version. There is no prevention by default that one uses an unsupported kubectl version unless you use `kubectl --match-server-version` explicitly.

## Workaround

We use [asdf kubectl](https://github.com/asdf-community/asdf-kubectl) to switch between `kubectl` versions by adding `.tool-versions` to folders that automatically switch between kubectl versions. For example:

- folder `cluster-a`: kubectl 1.29.12
- folder `cluster-b`: kubectl 1.28.15

## Suggested Solution
It would be nice to be able to specify the local kubectl version/path in the `kubeconfig` file. For the moment there is no such field in `kubeconfig.v1`: https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/.

I would suggest to extend `cluster` object by an `kubectl-client` attribute. It would look like this:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://1.2.3.4
  name: cluster-a
  kubectl-client: /path/to/kubectl/1.29.12
- cluster:
    server: https://5.6.7.8
  name: cluster-b
  kubectl-client: /path/to/kubectl/1.29.12
current-context: ""
kind: Config
preferences: {}
```

This general solution would make it possible to use different kubectl versions (binaries) per cluster. So one could use `asdf`, `update-alternatives`, `brew` etc.

If this issue is accepted I can build it and open a MR. But I wanted to make sure that the effort is worth it. I am already a kubernetes contributor.
