### ISSUE TITLE
Make `explain --recursive=true` produce all the descriptions in a machine-readable format (like YAML or JSON)

### ISSUE THREAD

**Issue by jakub-mikians-airspace-intelligence** [kubernetes/kubectl#1734]
**What would you like to be added**:

I would like to make `kubectl explain` in recursive mode to produce the exhaustive documentation of all the fields in a format that can be easily consumed by other tools. The output could be JSON or YAML.

**Why is this needed**:

I work on an autocompletion for Kubernetes resource templates (and helm templates). I need to learn the structure of all the possible fields. The recursive mode of `explain` command is perfect for this task, but has two drawbacks:
1. It does not produce full textual description, as non-recursive mode does
2. The output format needs custom handling, i.e. it's not a regular YAML (or JSON).

Ideally, I'd like to make the `explain` produce machine-readable output similar to the following:

```yaml
% kubectl explain deployment --recursive=true --output=yaml

kind: Deployment
description: Description of Deployment Kind.
fields:
- spec:
    type: Object
    required: false
    description: Specification of the desired behavior of the Deployment.
    fields:
    - minReadySeconds:
        type: integer
        required: false
        description: Minimum number of seconds for which a newly created pod (...)


# ... continue recursively for all the fields.   

```
