### ISSUE TITLE
Support autocompletion for `kuberc` aliases

### ISSUE THREAD

**Issue by hendrikKahl** [kubernetes/kubectl#1737]
**What would you like to be added**:

It would be great, if aliases in a `kuberc` file would trigger / work with regular `kubectl` autocompletion.

**Why is this needed**:

For generic aliases autocompletion would super useful. For example, an alias like the following would be even more useful, if autocompletion would work for both kind and resource names.

```yaml
  - name: gs
    command: get
    flags:
    - name: sort-by
      default: '{..creationTimestamp}'
```
