### ISSUE TITLE
kubectl apply with "--selector" fails if an unrelated label is set to Null

### ISSUE THREAD

**Issue by fjolublar** [kubernetes/kubectl#1743]
**What happened**:

If you have a resource with 2+ labels and one of the labels is set to `Null` or is empty `kubectl apply` works with no issues.

If you try to apply the resource using a selector `-l` the apply command fails with not so useful error message:

```sh
error: no objects passed to apply
```

**What you expected to happen**:

The filtering should work. 

The existing error message caused confusion because the label that we are searching for is actually set and we would expect that the filtering would find that resource.

**How to reproduce it (as minimally and precisely as possible)**:

Create a `test_file.yaml` with a CM resource definition.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  labels:
    label_a: null
    label_b: "bar"
    app.kubernetes.io/version: "v1.0.0"
data:
  config_key_1: "value1"
```

```sh
>> kubectl apply -f test_file.yaml
configmap/test-config created
```

If you try to apply the resource using a selector `-l` the apply command fails with not so useful error message:

```sh
>> kubectl apply -f test_file.yaml -l='label_b=bar'
error: no objects passed to apply
```

The `label_a` being Null/missing is causing issues with the `-l` label selector, even though `label_b` is being filtered.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): Client Version: v1.30.5, Server Version: v1.31.4
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): Darwin 24.4.0 Darwin Kernel Version 24.4.0:

**Comment by ardaguclu** [comment]
Do you mean this `kubectl apply -f test_file.yaml -l='label_b=bar'` works if test_file.yaml does not contain  `label_a: null`?.

I'm not sure that kubectl apply supports setting a label on command line (i.e. -l='label_b=bar') while you are passing a file to be applied (i.e. -f test_file.yaml).

**Comment by fjolublar** [comment]
> Do you mean this kubectl apply -f test_file.yaml -l='label_b=bar' works if test_file.yaml does not contain label_a: null?.

Yes. If the file does not contain `label_a: null` the apply with using the label selector works. 
But it shouldn't fail. 

As long as `kubectl apply -f test_file.yaml` works why shouldn't `kubectl apply -f test_file.yaml -l='label_b=bar'` work.

> I'm not sure that kubectl apply supports setting a label on command line

The `-l` argument is not used to `set` a label but to `filter` on the label: https://kubernetes.io/docs/reference/kubectl/generated/kubectl_apply/#options, i.e. select the resources that **contain** such label.

**Comment by ardaguclu** [comment]
Did you try `kubectl apply -l='label_b=bar' -f test_file.yaml`

**Comment by fjolublar** [comment]
> Did you try `kubectl apply -l='label_b=bar' -f test_file.yaml`

I don't think the order of the arguments matters 🤔. I tried it nevertheless and still fails.

**Comment by ardaguclu** [comment]
Thank you for testing. Could you please try `kubectl apply -l='label_b=bar' --server-side -f test_file.yaml`?

**Comment by ardaguclu** [comment]
I tried these steps and it didn't fail;

```
$ cat test_cm.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  labels:
    label_a: null
    label_b: "bar"
    app.kubernetes.io/version: "v1.0.0"
data:
  config_key_1: "value1"
```

firstly create resource;

```
$ kubectl apply --server-side -f test_cm.yaml 
configmap/test-config serverside-applied
```
After that I re-applied;
```
$ kubectl apply -f test_cm.yaml -l='label_b=bar' --server-side
configmap/test-config serverside-applied
```

I've used kubectl that is built from master branch.

**Comment by fjolublar** [comment]
I just tried it with **v1.33.0** and it works. Maybe there was a change in the newer versions of kubectl that fixes the problem!

```sh
kubectl version --client
Client Version: v1.33.0
```

client-side apply:

```sh
> kubectl apply -f test_cm.yaml -l='label_b=bar'
configmap/test-config created

> k get cm test-config -oyaml 
apiVersion: v1
data:
  config_key_1: value1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config_key_1":"value1"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/version":"v1.0.0","label_a":null,"label_b":"bar"},"name":"test-config","namespace":"default"}}
  creationTimestamp: "2025-05-12T10:06:08Z"
  labels:
    app.kubernetes.io/version: v1.0.0
    label_b: bar
  name: test-config
  namespace: default
  ...
```

server-side apply

```
>kubectl apply -f test_cm.yaml -l='label_b=bar' --server-side
configmap/test-config serverside-applied

>k get cm test-config -oyaml
apiVersion: v1
data:
  config_key_1: value1
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-12T10:07:28Z"
  labels:
    app.kubernetes.io/version: v1.0.0
    label_a: ""
    label_b: bar
  name: test-config
  namespace: default
  ...
```

For server-side the resource contains `label_a` set to explicitly to empty string `""` and in the client-side is completely missing.... but the original point was not with regards to differences to client-side vs server-side.

As far as I am concerned, it seems that the newer versions of kubectl do not show the issue with the label selector anymore and I just need to update my version to the latest.

Thank you for checking and your help @ardaguclu
