### ISSUE TITLE
No major and minor serverVersion-Information using Minikube v0.25.0 and K8s v1.9.0

### ISSUE THREAD

**Issue by PCQ** [kubernetes/kubectl#269]
Hello,
I am working on my Mac with the last minikube and kubernetes version
```
minikube version
> minikube version: v0.25.0
```
If have started minikube with
`minikube start --kubernetes-version v1.9.0`

But when I use kubectl to get the k8s version I only get empty Strings as minor and major serverVersion

```
kubectl version -o yaml
clientVersion:
  buildDate: 2018-01-04T11:52:23Z
  compiler: gc
  gitCommit: 3a1c9449a956b6026f075fa3134ff92f7d55f812
  gitTreeState: clean
  gitVersion: v1.9.1
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-01-26T19:04:38Z
  compiler: gc
  gitCommit: 925c127ec6b946659ad0fd596fa959be43f0cc05
  gitTreeState: clean
  gitVersion: v1.9.0
  goVersion: go1.9.1
  major: ""
  minor: ""
  platform: linux/amd64`

```

I am using this informations in my Unit-Test to validate that the cluster is running in the correct version.
