### ISSUE TITLE
Use Internal Error Library throughout Application to Display More Descriptive Error Messages (8)

### ISSUE THREAD

**Issue by seans3** [kubernetes/kubectl#278]
- [ ] Check correctness of PATCH - that it applies correctly to an object that it finds
- [ ] Resources parse as objects
- [ ] Options are well formed - ApplicationManifest schema parses
- [ ] replacement for lint. lint is going to call this 
- [x] hierarchy of errors 
- [x] may depend on technical debt (file system) issue

e.g.

Filenot found errors

**Comment by mengqiy** [comment]
One optional checking we may want to add is:

Validate all the field keys in the yaml are valid.
e.g.
```
apiVersion: manifest.k8s.io/v1alpha1
kind: Manifest
metadata:
  name: mysql
namePrefix: mengqiy-
# This key is wrong. It should be `objectLabels`.
# json decoder will drop this field silently as an unknown field.
# If we don't warning user about this. The user will get an empty `objectLabels` field after json unmarshal.
objectLabel: 
  app: myapp
resources:
  - deployment.yaml
```
