### ISSUE TITLE
[kinflate] use namePrefix in every reference/direct link

### ISSUE THREAD

**Issue by ant31** [kubernetes/kubectl#293]
I have some following resources:
one ingress, one svc
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: webapp
  name: webapp
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    k8s-app: webapp
  type: ClusterIP
```
and
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp
spec:
  rules:
  - host: webapp-example.com
    http:
      paths:
      - backend:
          serviceName: webapp
          servicePort: 5000
```

In this case, using `namePrefix` isn't practical because I have to edit manually the svc:
```
- backend:
          serviceName: $namePrefix-webapp
          servicePort: 5000
```

I would expect a replacement in the serviceName too
