### ISSUE TITLE
Make update name reference and patching works when there are multiple layers

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubectl#347]

**Comment by Liujingfang1** [comment]
In our example-example, we can run kubectl apply after inflating the customized base [kinflate/example-ldap-customized](https://github.com/kinflate/example-ldap-customized). The pod can get started correctly and adding/searching/deleting user all work as expected. However, the [staging and production instances](https://github.com/kinflate/example-ldap-instances) don't work since the nameprefix added in staing/production is not applied to name reference in the base layer.

More details:
```
$ kinflate inflate -f staging | kubectl apply -f -
configmap "staging-env-config-m2fht2h86b" created
configmap "staging-my-ldap-configmap-m6h4577g85" created
service "staging-my-ldap-service" created
deployment "staging-my-ldap" created
```
In the kinflate inflate output, we have
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: ldap
  name: staging-my-ldap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - args:
        - --copy-service
        image: osixia/openldap:1.1.11
        name: ldap
        ports:
        - containerPort: 389
          name: openldap
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: ldap-data
        - mountPath: /etc/ldap/slapd.d
          name: ldap-config
        - mountPath: /container/service/slapd/assets/certs
          name: ldap-certs
        - mountPath: /container/environment/01-custom
          name: configmap-volume
        - mountPath: /container/run
          name: container-run
      volumes:
      - emptyDir: {}
        name: ldap-data
      - emptyDir: {}
        name: ldap-config
      - emptyDir: {}
        name: ldap-certs
      - configMap:
          name: my-ldap-configmap-m6h4577g85
        name: configmap-volume
      - emptyDir: {}
        name: container-run
```
The configmap name `my-ldap-configmap-m6h4577g85` misses a `staging-` nameprefix.

As a result, the pod failed to mount the configmap-volume and the container couldn't get started.
