### ISSUE TITLE
kubectl reject annotation information without any warning

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubectl#378]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
/kind bug

**Kubernetes version** (use `kubectl version`):
master

**What happened**:
If we use `k create -f <file name> --save-config=true` or `kubectl apply <file name>`, and this file have annotations with type not `map[string]string`, then kubectl will quietly reject those annotations.

For example, you have a yaml described object wich annotation is: 
```yaml
metadata:
  name: test
  annotations:
    a: haha
    b: 1
```
We can see `b: 1` is not a correct annotation type. Then you use `kubectl apply` or `kubectl create --save-config` create this object, you will get an object with annotations like:
```yaml
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"test","namespace":"default"}}
```

And if you already have this object with annotations, after the `kubectl apply` command, the annotation will be cleared.

**What you expected to happen**:
In this case, kubectl should error out, with an err `invalid annotation` or something else.

**How to reproduce it** (as minimally and precisely as possible):
1. Create a file with content like:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: test
  annotations:
    a: haha
    b: 1
```
2. Use `k create -f <file name> --save-config=true` or `kubectl apply <file name>` to create this object.
3. Check the new created object annotations.

**Anything else we need to know**:
