### ISSUE TITLE
Error describing cronjobs with kubectl v1.10+

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/kubectl#487]
/kind bug
/sig cli
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** 

kubectl describe cronjob
"the server could not find the requested resource"
**Note:** Possibly related to #426 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):

Impacted Client Versions:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
```

Server Versions Tested:
```
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.9-gke.1", GitCommit:"c205eb8319d25aa46b1eb39b6c1d2bc5d1a49fae", GitTreeState:"clean", BuildDate:"2018-03-13T17:49:52Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**: minikube v0.26.1 and GKE with v1.8.9-gke.1 (will list minikube)
- **Cloud provider or hardware configuration**:  minikbue
- **OS** (e.g. from /etc/os-release): Buildroot
- **Kernel** (e.g. `uname -a`): Linux minikube 4.9.64 #1 SMP Fri Mar 30 21:27:22 UTC 2018 x86_64 GNU/Linux
- **Install tools**: minikube

**What happened**: 
Attempting to describe a cronjob will result in the following error:
```
Error from server (NotFound): the server could not find the requested resource
```
Switching to an older client, pre v1.10.0 works as intended with no error thrown. This was tested with kubectl versions 1.93. and 1.9.6
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T20:49:12Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
```

**What you expected to happen**:
Return the description of a cronjob

**How to reproduce it** (as minimally and precisely as possible):
Create and then describe a cronjob, in testing I used the below example:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-error-example
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          containers:
          - name: hello
            image: alpine:latest
            command: ["/bin/sh", "-c"]
            args: ["echo hello from $HOSTNAME!"]
          restartPolicy: Never
```

Command to describe
```
$ kubectl describe cronjob cronjob-error-example
```
