### ISSUE TITLE
Possible to bypass Service validation via "apply", loses declarative spec and locks down the object forever

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#491]
**Kubernetes version** (use `kubectl version`): 1.10.2

**What happened**:

I have managed to have "kubectl apply":

1. **bypass the  corev1.Service validation** (prevents you from specifying both UDP/TCP ports if `spec.type:LoadBalancer`),
2. have items in my declarative specification **was silently ignored and not applied**,
3. break my Service object **broken and no further `apply` works anymore**.

**How to reproduce it** (as minimally and precisely as possible):

1.  "kubectl apply" this yaml file, notice it is denied with error `"spec.ports: Invalid value: []core.ServicePort{...}: cannot create an external load balancer with mix protocols"`

    ```yaml
    kind: Service
    apiVersion: v1
    metadata:
    name: foo-lb
    spec:
    type: LoadBalancer
    selector:
        app: foo
    ports:
    - name: foo1
        port: 1053
        targetPort: 1053
        protocol: TCP
    - name: foo2
        port: 1053
        targetPort: 1053
        protocol: UDP
    ```

2. Delete the UDP port `foo2` and retry "kubectl apply", it should work (as expected)

    ```yaml
    kind: Service
    apiVersion: v1
    metadata:
    name: foo-lb
    spec:
    type: LoadBalancer
    selector:
        app: foo
    ports:
    - name: foo1
        port: 1053
        targetPort: 1053
        protocol: TCP
    ```

1. Now, use the YAML back in (1) with both `foo1` and `foo2` ports, and run
   kubectl apply, it will silently succeed (**UNEXPECTED!**)

    ```
    $ kubectl apply -f foo-lb.yaml
    service "foo-lb" configured
    ```

1. Inspect the object, and note that:

    -  `ports` section contains only `foo1` (**UNEXPECTED!** the specified UDP
       port is ignored)
    -  `kubectl.kubernetes.io/last-applied-configuration` annotation contains
       the spec with `foo2` (UDP) port.

1. **Now here's the real problematic part:** Somehow your UDP&TCP config was
   accepted above, but let's say you're trying to update your Service spec.

   So take the YAML in Step (2) that has only `foo1` TCP port and apply it
   and you'll get this weird error that is not at all accurate:

   ```sh
   $ kubectl apply -f foo-lb.yaml
   The Service "foo-lb" is invalid: spec.ports: Required value

1. :warning: There is **no way to recover** from this situation (as far as I can tell) unless
   you delete & recreate this `Service`.
