### ISSUE TITLE
--output=go-template returning weird ("<no value>") string, breaking integration

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#502]
kubectl v1.10.4

The following command prints `<no value>` to the screen:

```
kubectl config view --minify --flatten \
  -o=go-template='{{(index (index .clusters 0).cluster "certificate-authority-data")}}'
```

when the "clusters" field in the kubeconfig doesn't have the `"certificate-authority-data"` field, for example:

```
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: docker-for-desktop-cluster
```

`-o=go-template` should NOT cause a weird string value like `"<no value>"` to be printed to stdout. Instead this should print nothing and exit.

This is breaking integrations like `kubectl [...] | base64 --decode`, which works when a value is present, but `<no value>` is not an expected output from the specified template.
