### ISSUE TITLE
additionalPrinterColumns for CRD's doesn't work in k8s 1.11 for columns with array data

### ISSUE THREAD

**Issue by seans3** [kubernetes/kubectl#517]
**Kubernetes version** (use `kubectl version`): 1.11 (server-side printing)

**Environment**:
- **Cloud provider or hardware configuration**: GKE 

**Bug**
Reproduce using the following steps:

1) Create  CRD:

crd.yaml
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.example.istio.io
spec:
  group: example.istio.io
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  version: v1alpha1
  additionalPrinterColumns:
  - JSONPath: .spec.servers[*].hosts
    name: hosts
    type: string

```
```
$ kubectl apply -f crd.yaml
```
2) Create an instance of the CRD:

crd-instance.yaml
```
apiVersion: example.istio.io/v1alpha1
kind: Foo
metadata:
  name: foo0
spec:
  servers:
  - hosts:
    - foo.example.com
    - bar.example.com
  - hosts:
    - baz.example.com
```

```
$ kubectl apply -f crd-instance.yaml
```

3) Print instance of CRD:

```
$ kubectl get foos foo0
NAME      HOSTS
foo0      [foo.example.com bar.example.com]
```

### EXPECTED

Notice that only the first array of hosts is printed (missing second array `[baz.example.com]`). We would expect that both arrays would have been printed. If we specifically request the JSONPath, then it prints correctly.

```
$ kubectl get foos foo0 -o jsonpath='{.spec.servers[*].hosts}'
[foo.example.com bar.example.com] [baz.example.com]
```

**Comment by nikhita** [comment]
created a PR: https://github.com/kubernetes/kubernetes/pull/67079

**Comment by pipoe2h** [comment]
This is still happening with v1.16.8

obj.yaml
```
apiVersion: "k8s.josegomez.io/v1"
kind: StorageClusterPair
metadata:
  name: primary-dr
spec:
  remoteSites:
    - name: dr1
    - name: dr2
```

crd.yaml
```
[...]
      additionalPrinterColumns:
        - name: Sites
          type: string
          priority: 0
          jsonPath: .spec.remoteSites[*].name
          description: Remote sites enabled.
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
```

kubectl get storageclusterpair primary-dr
```
NAME         SITES   AGE
primary-dr   dr1     6m35s
```

kubectl get storageclusterpair primary-dr -o jsonpath='{.spec.remoteSites[*].name}'
```
dr1 dr2
```
