### ISSUE TITLE
port-forward should support named ports

### ISSUE THREAD

**Issue by mxey** [kubernetes/kubectl#538]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): v1.11.3

**Environment**:
- **Cloud provider or hardware configuration**: Libvirt
- **OS** (e.g. from /etc/os-release): Client on macOS 10.14.0, server CentOS 7
- **Kernel** (e.g. `uname -a`): 3.10.0-862.9.1.el7.x86_64
- **Install tools**: kubeadm
- **Others**:

**What happened**:

```
$ kubectl port-forward http-server http
error: Error parsing local port 'http': strconv.ParseUint: parsing "http": invalid syntax
```

**What you expected to happen**:

```
$ kubectl port-forward http-server http
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
```

**How to reproduce it** (as minimally and precisely as possible):

pod.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: http-server
spec:
  containers:
  - image: gcr.io/google_containers/defaultbackend:1.4
    imagePullPolicy: IfNotPresent
    name: default-http-backend
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
```

```
kubectl create -f pod.yaml
kubectl port-forward  http-server web
```
