### ISSUE TITLE
kubectl create secret docker-registry omits auth key in dockerconfigjson

### ISSUE THREAD

**Issue by TheKangaroo** [kubernetes/kubectl#571]
**BUG REPORT**

**Kubernetes version** (use `kubectl version`): 1.13.x

**Environment**:
- **OS**: kubectl on MacOS/hyperkube container

**What happened**:

I try to create a docker pull secret like: 
```
kubectl create secret docker-registry test --docker-server=registry.example.com  --docker-username=username --docker-password=password --docker-email=test@example.com --dry-run -oyaml
```
This creates an object like:
```
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJVc2VybmFtZSI6InVzZXJuYW1lIiwiUGFzc3dvcmQiOiJwYXNzd29yZCIsIkVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: test
type: kubernetes.io/dockerconfigjson
```
And the base64-decoded string looks like this:
```
# echo 'eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJVc2VybmFtZSI6InVzZXJuYW1lIiwiUGFzc3dvcmQiOiJwYXNzd29yZCIsIkVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSJ9fX0=' |base64 -D
{"auths":{"registry.example.com":{"Username":"username","Password":"password","Email":"test@example.com"}}}
```
Mind the missing auth key.

**What you expected to happen**:
When I run the same command with the kubelet 1.12.0 everything works as expected:
```
kubectl create secret docker-registry test --docker-server=registry.example.com  --docker-username=username --docker-password=password --docker-email=test@example.com --dry-run -oyaml
```
This creates an object like:
```
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwicGFzc3dvcmQiOiJwYXNzd29yZCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImF1dGgiOiJkWE5sY201aGJXVTZjR0Z6YzNkdmNtUT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: test
type: kubernetes.io/dockerconfigjson
```
And the base64-decoded string looks like this:
```
# echo 'eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwicGFzc3dvcmQiOiJwYXNzd29yZCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImF1dGgiOiJkWE5sY201aGJXVTZjR0Z6YzNkdmNtUT0ifX19' |base64 -D
{"auths":{"registry.example.com":{"username":"username","password":"password","email":"test@example.com","auth":"dXNlcm5hbWU6cGFzc3dvcmQ="}}}
```
This one creates the auth key.

**How to reproduce it** (as minimally and precisely as possible):
Run the command above with kubectl v1.12.x and 1.13.x 

**Anything else we need to know**:
I can reproduce it on my Mac and in the hyperkube docker container.
I ran it against an 1.11.5 cluster, ~~but try to test agains an newer cluster soon.~~
Same result against a 1.13.1 cluster.
