### ISSUE TITLE
Windows 10 WSL - "cannot allocate memory" when calling a plugin

### ISSUE THREAD

**Issue by jon-walton** [kubernetes/kubectl#603]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): windows; allocate

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Kubernetes version** (use `kubectl version`): ```Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}```

**Environment**:
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Windows 10.0.17763 / Ubuntu 18.04.2 LTS
- **Kernel** (e.g. `uname -a`): ```Linux DESKTOP-3I1L0FQ 4.4.0-17763-Microsoft #253-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux```
- **Install tools**:
- **Others**:

**What happened**:

kubectl often returns ```cannot allocate memory``` instead of executing a plugin. Calling the plugin directly always works.

**What you expected to happen**:

calling the plugin via kubectl to work as if called directly

**How to reproduce it** (as minimally and precisely as possible):

Use the example plugin from https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#example-plugin
```text
$ k plugin list
The following kubectl-compatible plugins are available:

/home/jon/.kube/plugins/kubectl-foo
```

kubectl often returns ```cannot allocate memory``` instead of executing the plugin.
```text
$ k foo
cannot allocate memory
$ k foo version
1.0.0
$ k foo version
cannot allocate memory
$ k foo version
cannot allocate memory
$ k foo
cannot allocate memory
$ k foo
cannot allocate memory
$ k foo
cannot allocate memory
$ k foo
cannot allocate memory
$ k foo
I am a plugin named kubectl-foo
$ k foo
cannot allocate memory
```

executing the plugin directly always works
```text
$ kubectl-foo version
1.0.0
$ kubectl-foo
I am a plugin named kubectl-foo
$ kubectl-foo version
1.0.0
$ kubectl-foo version
1.0.0
$ kubectl-foo version
1.0.0
$ kubectl-foo version
1.0.0
$ kubectl-foo version
1.0.0
```

**Anything else we need to know**:

This also happens with windows compatible plugins when called directly from Windows 10, rather then WSL; however it's easier for me to provide details using linux tooling.

Here's a `strace -o kubectl -ff -y kubectl foo version` 
[kubectl.zip](https://github.com/kubernetes/kubectl/files/2948451/kubectl.zip)

**Comment by jon-walton** [comment]
Here's a ```strace -o kubectl -ff -y kubectl foo version``` of it working
[kubectl-works.zip](https://github.com/kubernetes/kubectl/files/2948458/kubectl-works.zip)

**Comment by sawlanipradeep** [comment]
I am also having issue installing Krew on Windows and got here fromhttps://github.com/kubernetes-sigs/krew/issues/156  
@jon-walton Looking at the description, error message you have are for Linux. For windows I see following 
```
PS C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin> kubectl krew --help
not supported by windows
PS C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin>
```
I tried different plugins but same error.  kubectl version is this:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b
1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"windows/amd64"}
```
Windows version:  Microsoft Windows Server 2012 R2 Datacenter

**Comment by sawlanipradeep** [comment]
kubectl calls Exec which on windows returns error (https://golang.org/src/syscall/exec_windows.go)
May be kubectl should be using StartProcess instead of Exec on Windows.

**Comment by spacecat** [comment]
Also getting `not supported by windows`:

```
PS C:\krew-temp\krew> kubectl krew
not supported by windows
```

Ran the following command in an elevated PowerShell and it installed successfully:

`.\krew-windows_amd64.exe install --manifest=krew.yaml --archive=krew.zip`

```
clientVersion:
  buildDate: "2019-03-25T15:53:57Z"
  compiler: gc
  gitCommit: 641856db18352033a0d96dbc99153fa3b27298e5
  gitTreeState: clean
  gitVersion: v1.14.0
  goVersion: go1.12.1
  major: "1"
  minor: "14"
  platform: windows/amd64
serverVersion:
  buildDate: "2019-03-25T06:30:48Z"
  compiler: gc
  gitCommit: 16236ce91790d4c75b79f6ce96841db1c843e7d2
  gitTreeState: clean
  gitVersion: v1.11.9
  goVersion: go1.10.8
  major: "1"
  minor: "11"
  platform: linux/amd64
```

Windows 10 Pro
