### ISSUE TITLE
kubectl set env deletes namespace

### ISSUE THREAD

**Issue by dellintosh** [kubernetes/kubectl#639]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?**: `set env`, `namespace`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Kubernetes version** (use `kubectl version`): 
```console
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:36:43Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Example is run locally (`--local` flag)
- **OS** (e.g. from /etc/os-release): MacOS 10.13.6
- **Kernel** (e.g. `uname -a`): Darwin Kernel Version 17.7.0
- **Install tools**: 
- **Others**:

**What happened**: When running the following command against the provided deployment yaml, the output removes the `namespace` field from the yaml.

**What you expected to happen**: I expect the environment variable to be injected (or updated) but the rest of the deployment definition to remain the same, in this case the `namespace` (if set) value should not be removed.

**How to reproduce it** (as minimally and precisely as possible): 

Assuming that you have a local sample file `nginx-sample.yaml`: 

`nginx-sample.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-test
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 512Mi
            cpu: 200m
          limits:
            memory: 1Gi
            cpu: 400m
```

run the following command:

```console
$ kubectl set env -o yaml --local -f nginx-sample.yaml -e FOO=BAR
```
Notice that the output yaml has removed the `nginx-test` namespace:
```diff
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-deployment
- namespace: nginx-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - env:
+        - name: FOO
+          value: bar
        image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
```

**Anything else we need to know**: I have also attempted to add the namespace as an inline argument:
```console
$ kubectl set env --namespace=nginx-test -o yaml --local -f nginx-sample.yaml -e FOO=BAR
$ kubectl set env -n nginx-test -o yaml --local -f nginx-sample.yaml -e FOO=BAR
```
with the same results as above.
