### ISSUE TITLE
Example Configmap Invalid DNS Name

### ISSUE THREAD

**Issue by abhishekjiitr** [kubernetes/kubectl#642]
DOCUMENTATION BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: v1.14.1
Server Version: v1.13.3

**Environment**:

- **OS**: Ubuntu 19.03 (Disco Dingo)
- **Kernel**: 5.0.0-8-generic #9-Ubuntu SMP Tue Mar 12 21:58:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
Following the steps of *ConfigMaps From Files* example in _App Management_._Secrets & Configmaps_ Section, I executed `kubectl apply -k .` The command failed with the following error:
```
The ConfigMap "myApplicationProperties-fm2tc275t4" is invalid: metadata.name: Invalid value: "myApplicationProperties-fm2tc275t4": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
Same is the case with another ConfigMap named _myJavaServerEnvVars_
**What you expected to happen**:
A configmap named _myApplicationProperties_ to be created

**How to reproduce it** (as minimally and precisely as possible):
Apply this yaml using kustomize
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: myApplicationProperties
    files:
    - application.properties
```

**Anything else we need to know**:
Fix: Use a valid DNS Subdomain name, like _my_application_properties_ instead of _myApplicationProperties_
