### ISSUE TITLE
kubectl leaks tokens for configs created with the azure command line tools

### ISSUE THREAD

**Issue by mcasperson** [kubernetes/kubectl#667]
When connecting to an Azure AKS cluster, you run the command `az aks get-credentials` to generate a local `~/.kube/config` file. For whatever reason, this config file has both `client-certificate-data` and a `token`. When you run `kubectl config view`, the certificate data is redacted, but the token is displayed in plain text.

For example, this is an example of the result of running `kubectl config view` after running `az aks get-credentials`. Note the token is not redacted:

```
apiVersion: v1 
clusters: 
- cluster: 
    certificate-authority-data: REDACTED 
    server: https://urlgoeshere:443 
  name: k8scluster
contexts: 
- context: 
    cluster: k8scluster
    namespace: default 
    user: clusterUser_k8scluster_k8scluster
  name: k8scluster
current-context: k8scluster
kind: Config 
preferences: {} 
users: 
- name: clusterUser_k8scluster_k8scluster
  user: 
    client-certificate-data: REDACTED 
    client-key-data: REDACTED 
    token: 12345678ABCDEFG
```
