### ISSUE TITLE
kubectl delete all -l foo=bar - does not delete ingress

### ISSUE THREAD

**Issue by Vrtak-CZ** [kubernetes/kubectl#7]
```
kubectl delete all -l foo=bar
```

does not delete ingress with label `foo=bar`.

**Comment by mengqiy** [comment]
I think this is because of ingress is a luster scoped resource.
https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all

**Comment by pwittrock** [comment]
Ingress [is namespaced](https://kubernetes.io/docs/api-reference/v1.6/#create-138).  `--all` probably uses a static list somewhere.

**Comment by Vrtak-CZ** [comment]
Yes but when i use `kubectl delete all -l foo=bar -n baz` it doesn't work either.

**Comment by pwittrock** [comment]
My comment was in response to @mengqiy.

@bowei is this your team?

**Comment by bowei** [comment]
yes -- cc: @nicksardo

**Comment by bowei** [comment]
@Vrtak-CZ : do you have a minimal repro we can try? (e.g. ingress YAML)

**Comment by Vrtak-CZ** [comment]
sure

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: awesome-ingress
  namespace: foo
  labels:
    app: bar
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: awesome-service
          servicePort: 3000
```

and then I try `kubectl delete all -l app=bar -n foo`
