### ISSUE TITLE
"kubectl create role" ignores --namespace flag

### ISSUE THREAD

**Issue by stephen-dexda** [kubernetes/kubectl#705]
Unlike many (most?) other `kubectl create` commands, `kubectl create role` ignores `--namespace` (`-n`).

This can result in unexpected/undesirable behaviour when e.g. piped to `kubectl apply -f -`, where the role is created in the wrong namespace (i.e. the default one).

Example command:

```bash
kubectl -n foo-ns create role foo-role --verb=list --resource=pods --dry-run=true -o yaml
```

Actual:

```yaml
kind: Role
metadata:
  creationTimestamp: null
  name: foo-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
```

Expected:

```yaml
kind: Role
metadata:
  creationTimestamp: null
  name: foo-role
  namespace: foo-ns
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
```
