### ISSUE TITLE
kubectl create clusterrolebinding does not use ClusterRole defined rbac api vesion

### ISSUE THREAD

**Issue by gjemp** [kubernetes/kubectl#726]
Running k8s 1.15.3

I have ClusterRole like that :
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-subaru: "true"
    rbac.authorization.k8s.io/aggregate-subaru-read: "true"
  name: namespace-reading-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - watch
  - list
  - get
```
and i have serviceaccount like that:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testrole
  namespace: default
secrets:
- name: testrole-token-ccvvt
```

now i run following :
kubectl create clusterrolebinding testrole-ns-clusterrrole-binding --clusterrole=namespace-reading-clusterrole --serviceaccount=default:testrole --dry-run -o yaml | /usr/local/bin/kubectl auth reconcile -f -

*Expected*
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: testrole-ns-clusterrrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-reading-clusterrole
subjects:
- kind: ServiceAccount
  name: testrole
  namespace: default
```

*Actual:*
It creates following  CRB
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: testrole-ns-clusterrrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-reading-clusterrole
subjects:
- kind: ServiceAccount
  name: testrole
  namespace: default
```
It fails with message : error: only rbac.authorization.k8s.io/v1 is supported: not *v1beta1.ClusterRoleBinding
