### ISSUE TITLE
kubectl apply -k <dir> not consistent with kubectl apply -f <dir>

### ISSUE THREAD

**Issue by damarshall** [kubernetes/kubectl#741]
Kubectl book implies `apply -k` should be used against directories with __kustomization.yaml__ files while `apply -f` should be run against directories without kustomization.

From the [__kubectl__ book](https://kubectl.docs.kubernetes.io/pages/app_management/apply.html):

> Users run Apply on directories containing kustomization.yaml files using -k or on raw ResourceConfig files using -f.

In practice, `apply -k` will only operate against manifests containing certain resource types such as services and deployments.

## Steps to Reproduce

Verifying a recent version of `kubectl`:

```
 kubectl version --short
Client Version: v1.16.2
Server Version: v1.15.4-k3s.1
```

take the [standard deployment manifests from metrics server](https://github.com/kubernetes-incubator/metrics-server/tree/master/deploy/1.8%2B) and copy into a local directory.

A dry run shows expected behavior for `apply -f`:

```
kubectl --dry-run=True apply -f .
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader configured (dry run)
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator configured (dry run)
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader configured (dry run)
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io configured (dry run)
serviceaccount/metrics-server configured (dry run)
deployment.apps/metrics-server configured (dry run)
service/metrics-server configured (dry run)
clusterrole.rbac.authorization.k8s.io/system:metrics-server configured (dry run)
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server configured (dry run)
```

Now create a simple __kustomization.yaml__, in the same directory (in this case to use the image for an alternate architecture):

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: k8s.gcr.io/metrics-server-amd64 # match images with this name
    newName: k8s.gcr.io/metrics-server-arm64 # override the name
resources:
- metrics-server-deployment.yaml
```

Now perform a dry-run with `apply -k` to see inconsistent behavior:

```
kubectl --dry-run=True apply -k .
serviceaccount/metrics-server configured (dry run)
deployment.apps/metrics-server configured (dry run)
```
### Expected behavior

Expected behavior is consistency between the effects of `apply -f` and `apply -k`. The steps above should produce this output:

```
kubectl --dry-run=True apply -k .
clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader configured (dry run)
clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator configured (dry run)
rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader configured (dry run)
apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io configured (dry run)
serviceaccount/metrics-server configured (dry run)
deployment.apps/metrics-server configured (dry run)
service/metrics-server configured (dry run)
clusterrole.rbac.authorization.k8s.io/system:metrics-server configured (dry run)
clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server configured (dry run)
```

**Comment by damarshall** [comment]
This turns out to be a documentation deficit. `apply -k` on a directory will only process manifests mentioned in the _resources_ section of the __kustomization.yaml__ file.

Expected behavior is achieved if the __kustomization__ file above is amended and all manifests in the directory are referenced, as follows:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: k8s.gcr.io/metrics-server-amd64 # match images with this name
    newName: k8s.gcr.io/metrics-server-arm64 # override the name
resources:
- aggregated-metrics-reader.yaml  
- auth-delegator.yaml  
- auth-reader.yaml
- metrics-apiservice.yaml  
- metrics-server-deployment.yaml  
- metrics-server-service.yaml
- resource-reader.yaml
```

I'd be happy to submit a documentation patch if helpful.
