### ISSUE TITLE
kubectl does not send Authorization header (or use specified auth plugin) over plain HTTP

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubectl#744]
I have a GKE cluster kubeconfig, so its user section looks like this:

```yaml
- name: foo
  user:
    auth-provider:
      config:
        access-token: --REDACTED-REDACTED--
        cmd-args: config config-helper --format=json
        cmd-path: /Users/ahmetb/.homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: "2019-10-24T01:33:17Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

When I snoop on kubectl requests using `mitmproxy`, I see the `Authorization` header and Bearer token sent with the requests.

Note that GKE masters use https:// with self signed certs (included in kubeconfig).

However, when I point the kubeconfig to a local server e.g. `server: http://localhost:8080` with the rest of the kubeconfig same, I notice that **no `Authorization` header is sent to the server**.

I have further confirmed this by making my localhost server serve using a self-signed TLS certificate, on `https://localhost:6433` and when I do that my local apiserver gets the `Authorization` header.

1. Is this expected?
2. Should this be documented? I spent a couple of hours trying to figure out why my local apiserver over http:// doesn't get Authorization header.

/kind bug
