### ISSUE TITLE
Unable to connect to the server: getting credentials: exec: exit status 255

### ISSUE THREAD

**Issue by b0nete** [kubernetes/kubectl#747]
Hello, i'm having this error when try get pods or any resource in my k8s cluster with kubectl.

> kubectl get pods
> 
> 'credentialScope'
> 
> 'credentialScope'
> 
> 'credentialScope'
> 
> 'credentialScope'
> 
> 'credentialScope'
> Unable to connect to the server: getting credentials: exec: exit status 255

The error only appears with EKS, with GKS cluster works fine.
I've uninstalled aws-cli, aws-iam-authenticator and kubectl and reinstall but error continues.

aws-cli is working fine, I can list the clusters, s3 buckets, etc with.
Also deleted ~/.kube/config and recreated with aws eks update-kubeconfig --name NAME but follow without work.

Versions:
aws-cli 1.16.254
aws-iam-authenticator-bin 0.4.0
kubectl 1.15.2

I hope help, thanks.

**Comment by justenspring** [comment]
Exact same issue here, took the same remedial steps without any luck. I can also run aws cli commands successfully in our multiple accounts, but receive this EKS error on every cluster. 

In my case, IAM is through SAML federated auth on a role. I'm not aware of any changes made in our environment over the weekend, but this worked on Friday so I'm not sure what to make of it.

Versions:
aws-cli 1.16.203
aws-iam-authenticator-bin 0.4.0
kubectl 1.16

**Comment by tmat-s** [comment]
I ran into same issue here.

In my case, removing aws-iam-authenticator from PATH and recreating kubeconfig via `aws eks update-kubeconfig` seem to have resolved the issue. 

kubectl can interact with EKS cluster without aws-iam-authenticator now.

Versions:
MacOS 10.14.2
aws-cli 1.16.268
kubectl v1.16.2

**Comment by justenspring** [comment]
Dang, I just tried those steps but no luck, still getting the 'credentialScope'...exit status 255 error. 

Do you know if there's any way to figure out more detailed info on what the root error is?

(Forgot to add, I'm also on 10.14 of MacOS)

**Comment by tmat-s** [comment]
You can get more detailed logs by adding `-v 8` option to kubectl.
In my case, initial connection to EKS endpoint seems to have failed with 255 error.
According to [this issue](https://github.com/aws/aws-cli/issues/3744) and official document, error 255 can be caused by syntax error in kubeconfig.
> The 255 indicates the command failed and there were errors thrown by either the CLI or by the service the request was made to.

So, at least in my case, it was definitely aws-related issue.
Have you tried deleting(renaming) `$HOME/.kube` completely , then recreating kubeconfig?

**Comment by b0nete** [comment]
> You can get more detailed logs by adding `-v 8` option to kubectl.
> In my case, initial connection to EKS endpoint seems to have failed with 255 error.
> According to [this issue](https://github.com/aws/aws-cli/issues/3744) and official document, error 255 can be caused by syntax error in kubeconfig.
> 
> > The 255 indicates the command failed and there were errors thrown by either the CLI or by the service the request was made to.
> 
> So, at least in my case, it was definitely aws-related issue.
> Have you tried deleting(renaming) `$HOME/.kube` completely , then recreating kubeconfig?

I tried remove $HOME/.kube and recreate config with aws eks update-kubeconfig but the error persisted. 
Now i could solve this problem change the follow lines in kubeconfig as this thread says.
[https://itnext.io/kubernetes-part-4-aws-eks-authentification-aws-iam-authenticator-and-aws-iam-5985d5af9317](url)

Change this:
```
...
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - mobilebackend-dev-eks-0-cluster
      command: aws
...
```

for this:
```
...
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
        - token
        - -i
        - mobilebackend-dev-eks-0-cluster
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: arseniy
...

```
