### ISSUE TITLE
port-forward: named port not working with service

### ISSUE THREAD

**Issue by Dominik-K** [kubernetes/kubectl#752]
**Kubernetes version** (use `kubectl version`): `v1.16.2`
**What happened**:
```
$ kubectl port-forward service/prometheus-k8s web
error: error parsing local port 'web': strconv.ParseUint: parsing "web": invalid syntax
```
**What you expected to happen**:
```
$ kubectl port-forward service/prometheus-k8s web
Forwarding from 127.0.0.1:9090 -> 9090
Forwarding from [::1]:9090 -> 9090
```
It works fine for types `pod` & `statefulset` (or `deployment` in other cases).

**How to reproduce it**:

`svc-and-pod.yaml`:
```
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus
  name: prometheus-k8s
spec: 
  containers:
    - image: quay.io/prometheus/prometheus:v2.7.2
      name: prometheus
      ports:
      - containerPort: 9090
        name: web
        protocol: TCP
```

```
kubectl apply -f svc-and-pod.yaml
kubectl port-forward service/prometheus-k8s web
```

**Related issues**:
https://github.com/kubernetes/kubectl/issues/538
