### ISSUE TITLE
Kubectl -k fails with error "SliceFromPatches: evalsymlink failure on '/etc/kubernetes/kustomize/calico/apiVersion" - kustomize build reports no issues

### ISSUE THREAD

**Issue by oivindoh** [kubernetes/kubectl#783]
I have a a directory /etc/kubernetes/kustomize/calico that contains two files:

- calico.yaml (carbon copy of https://docs.projectcalico.org/v3.10/manifests/calico.yaml)
- kustomization.yaml

The expected outcome is from `kubectl apply -k /etc/kubernetes/kustomize/calico` to apply kustomized manifests to the cluster.

The actual outcome is the following error:

```
error: SliceFromPatches: evalsymlink failure on '/etc/kubernetes/kustomize/calico/apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: calico-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: calico-node
        env:
        - name: CALICO_IPV4POOL_CIDR
          value: "10.2.0.0/24"' : lstat /etc/kubernetes/kustomize/calico/apiVersion: apps: no such file or directory
```

**kustomization.yaml content:**

```yaml
resources:
- calico.yaml
# https://github.com/kubernetes-sigs/kustomize/issues/1373
# works with patches in kustomze, but kubectl -k barfs
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: calico-node
    namespace: kube-system
  spec:
    template:
      spec:
        containers:
        - name: calico-node
          env:
            name: CALICO_IPV4POOL_CIDR
            value: "10.2.0.0/24"

```

`kustomize build /etc/kubernetes/kustomize/calico/` runs and updates the CALICO_IPV4POOL_CIDR environment variable in the calico-node DaemonSets calico-node container as expected:

```
kustomize build /etc/kubernetes/kustomize/calico/ | grep -A 1 IPV4POOL_CIDR
          name: CALICO_IPV4POOL_CIDR
          value: 10.2.0.0/24
```

Kubectl has no problem applying the manifests  when piped from kustomize: `kustomize build /etc/kubernetes/kustomize/calico | kubectl apply -f -`:

```
../kustomize build /etc/kubernetes/kustomize/calico | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
serviceaccount/calico-kube-controllers created
serviceaccount/calico-node created
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrole.rbac.authorization.k8s.io/calico-node created
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrolebinding.rbac.authorization.k8s.io/calico-node created
configmap/calico-config created
deployment.apps/calico-kube-controllers created
daemonset.apps/calico-node created
```

Version data:

```json
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
