### ISSUE TITLE
kubectl apply set-last-applied does not use manifest's `metadata.namespace`

### ISSUE THREAD

**Issue by migueloller** [kubernetes/kubectl#787]
### What happened
Running `kubectl apply set-last-applied` after successfully running `kubectl apply` fails with message: `Error from server (NotFound): ...`. The reason for this is that while `kubectl apply` uses the manifests' `metadata.namespace` to update the resources, `kubectl apply set-last-applied` uses the default namespace for the current context of the kubeconfig.

### Expected Behavior
`kubectl apply set-last-applied` should use the manifests' `metadata.namespace` just like `kubectl apply` does.

#### `test-svc.yaml`
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: test
spec:
  type: ExternalName
  externalName: www.example.com
```

```bash
kubectl config set-context --current --namespace=default
kubectl apply -f ./test-svc.yaml
kubectl apply set-last-applied -f ./test-svc.yaml
```
