### ISSUE TITLE
kubectl get events --watch doesn't print messages

### ISSUE THREAD

**Issue by tsubasaxZZZ** [kubernetes/kubectl#793]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

`is:issue "kubectl get events"`

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): 
```
clientVersion:
  buildDate: "2019-12-07T21:20:10Z"
  compiler: gc
  gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
  gitTreeState: clean
  gitVersion: v1.17.0
  goVersion: go1.13.4
  major: "1"
  minor: "17"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-09-18T14:34:46Z"
  compiler: gc
  gitCommit: 25074a190ef2a07d8b0ed38734f2cb373edfb868
  gitTreeState: clean
  gitVersion: v1.13.11
  goVersion: go1.11.13
  major: "1"
  minor: "13"
  platform: linux/amd64
```

**Environment**:

* **Cloud provider or hardware configuration**: Azure Kubernetes Service
* **OS** (e.g. from /etc/os-release): 
* **Kernel** (e.g. `uname -a`): 
* **Install tools**:
* **Others**: kubecrl is on Windows Subsystem for Linux

**What happened**:

```
$ kubectl get events -w
LAST SEEN   TYPE      REASON                KIND         MESSAGE
42m         Normal    SuccessfulCreate      ReplicaSet   (combined from similar events): Created pod: nginx-5c7588df-p24zh
46m         Normal    ScalingReplicaSet     Deployment   Scaled up replica set nginx-5c7588df to 3
44m         Normal    ScalingReplicaSet     Deployment   Scaled down replica set nginx-5c7588df to 3
43m         Normal    ScalingReplicaSet     Deployment   Scaled up replica set nginx-5c7588df to 6
59m         Normal    DeletedLoadBalancer   Service      Deleted load balancer

NAME                       AGE               <---------------- MESSAGE column is missing
aks-ssh.15e66a30543fc247   0s
aks-ssh.15e66a309034736f   0s
aks-ssh.15e66a312f47ef25   0s
aks-ssh.15e66a3140939369   0s
```

**What you expected to happen**:

I expect the command to behave output message add events.

**How to reproduce it** (as minimally and precisely as possible):
See examples above.

**Anything else we need to know**:
