### ISSUE TITLE
kubectl replace doesn't work with immutable fields

### ISSUE THREAD

**Issue by pbecotte** [kubernetes/kubectl#798]
`kubectl replace` doesn't work on service objects unless `ClusterIP` is specified. Not sure what the correct behavior should be? Came across this looking at issues with `helm update --force` not working if there is a service in the app.
https://github.com/helm/helm/issues/7350

```
#svc.yaml
kind: Service
apiVersion: v1
metadata:
  name: svc
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - name: blah
      port: 8080
```

```
$ kubectl apply -f svc.yaml
service/svc configured
$ kubectl replace -f svc.yaml 
The Service "svc" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```
