### ISSUE TITLE
Random ordering of annotations in describe ingress

### ISSUE THREAD

**Issue by jglick** [kubernetes/kubectl#802]
Testing against Microk8s

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-10T03:03:57Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

`kubectl apply -f` the following:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/app-root: /demo
    nginx.ingress.kubernetes.io/proxy-body-size: 99m
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
          serviceName: demo
          servicePort: 80
```

Now if you

```bash
watch kubectl describe ing
```

you will see the annotations dance around randomly. Sometimes you migh see

```
  nginx.ingress.kubernetes.io/ssl-redirect:          false
  kubectl.kubernetes.io/last-applied-configuration:  {…}

  kubernetes.io/ingress.class:                          nginx
  kubernetes.io/tls-acme:                               false
  nginx.ingress.kubernetes.io/app-root:                 /demo
  nginx.ingress.kubernetes.io/proxy-body-size:          99m
  nginx.ingress.kubernetes.io/proxy-request-buffering:  off
```

and at other times

```
  kubectl.kubernetes.io/last-applied-configuration:  {…}

  kubernetes.io/ingress.class:                          nginx
  kubernetes.io/tls-acme:                               false
  nginx.ingress.kubernetes.io/app-root:                 /demo
  nginx.ingress.kubernetes.io/proxy-body-size:          99m
  nginx.ingress.kubernetes.io/proxy-request-buffering:  off
  nginx.ingress.kubernetes.io/ssl-redirect:             false
```

I would expect the displayed order to be stable, preferably lexicographically sorted.

I believe the issue is that https://github.com/kubernetes/kubernetes/blob/b95d571e32294047a5fb9ca93ee4e394f6765308/staging/src/k8s.io/kubectl/pkg/describe/versioned/describe.go#L2412-L2439 is not simply using https://github.com/kubernetes/kubernetes/blob/b95d571e32294047a5fb9ca93ee4e394f6765308/staging/src/k8s.io/kubectl/pkg/describe/versioned/describe.go#L4668

```go
printAnnotationsMultiline(w, "Annotations", ing.Annotations)
```

like every other resources type I could find.
