### ISSUE TITLE
kubectl does not allow multiple extra-scopes with --auth-provider-arg

### ISSUE THREAD

**Issue by joachimmathes** [kubernetes/kubectl#807]
## kubectl version

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

## What I do

```sh
kubectl config set-credentials system-user \
--auth-provider oidc \
--auth-provider-arg=idp-issuer-url=https://login.foo.bar/auth/realms/system \
--auth-provider-arg=client-id=k8s-system-api \
--auth-provider-arg=client-secret=11111111-1111-1111-1111-111111111111 \
--auth-provider-arg=extra-scopes=openid,foo,bar
```

## What I expect

In `~/.kube/config.yaml` key `extra-scopes` should have value `openid,foo,bar`

```
users:
- name: system-user
  user:
    auth-provider:
      config:
        client-id: k8s-system-api
        client-secret: 11111111-1111-1111-1111-111111111111
        extra-scopes: openid,foo,bar
        idp-issuer-url: https://login.boo.bar/auth/realms/system
```

## What it does

```
...

Use "kubectl options" for a list of global command-line options (applies to all commands).
error: Error: invalid auth-provider-arg format: foo, bar
```
Single or double quoting the csv doesn't help either.

## Workaround

1. Run `kubectl` with single extra scope:
   ```
   --auth-provider-arg=extra-scopes=openid
   ```
2. Add additional scopes `foo,bar` to key `extra-scopes` in `~/.kube/config.yaml` manually.
