### ISSUE TITLE
Support KUBECONFIG_BASE64 env

### ISSUE THREAD

**Issue by johnjjung** [kubernetes/kubectl#825]
`KUBECONFIG=~/.kube/config`

This is a great feature. However, it's really annoying for CI/CD pipelines where you have to get the file. Can you guys please support multiline environment variables with a base64'd version of the kubeconfig variable that you want?

For example:

```
apiVersion: v1
kind: Config

clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://xxxx.xxxx.com
  name: xxxx

users:
- name: xxx
  user:
    client-key-data: xxxx
    token: xxxx

contexts:
- context:
    cluster: xxxx
    namespace: xxxx
    user: xxxx
  name: xxxx

current-context: xxxx
```

`KUBECONFIG_BASE64=YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCgpjbHVzdGVyczoKLSBjbHVzdGVyOgogICAgY2VydGlmaWNhdGUtYXV0aG9yaXR5LWRhdGE6IHh4eAogICAgc2VydmVyOiBodHRwczovL3h4eHgueHh4eC5jb20KICBuYW1lOiB4eHh4Cgp1c2VyczoKLSBuYW1lOiB4eHgKICB1c2VyOgogICAgY2xpZW50LWtleS1kYXRhOiB4eHh4CiAgICB0b2tlbjogeHh4eAoKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IHh4eHgKICAgIG5hbWVzcGFjZTogeHh4eAogICAgdXNlcjogeHh4eAogIG5hbWU6IHh4eHgKCmN1cnJlbnQtY29udGV4dDogeHh4eA==`
