### ISSUE TITLE
kubectl get pods table view displays targets incorrectly for type averageValue

### ISSUE THREAD

**Issue by phroggyy** [kubernetes/kubectl#839]
## Description

When creating a `HorizontalPodAutoscaler` of the apiVersion `autoscaling/v2beta2`, using an `Object` metric with an `averageValue` target, `kubectl get hpa` (default output format) incorrectly displays the targets as 0/0. `kubectl describe hpa` **does** correctly parse the average value out of the response.

## Steps to reproduce

YAML used:
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        describedObject:
          kind: ingress
          apiVersion: networking.k8s.io/v1beta1
          name: myapp
        target:
          type: AverageValue
          averageValue: 10 # we don't want more than 10rps per replica
        metric:
          name: requests_per_second
```

This particular example requires a custom metric `requests_per_second` which I'm creating with prometheus-adapter and nginx-ingress data.

## Current output
`kubectl describe hpa myapp` (correct)

```
Metrics:                                                                ( current / target )
  "requests_per_second" on ingress/myapp (target average value):        8611m / 10
```

`kubectl get hpa myapp` (incorrect)

```
NAME          REFERENCE                TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
myapp         Deployment/myapp         0/0       1         10        4          74m
```

## Expected Behaviour

`kubectl get hpa` outputs the table in the correct format:

```
NAME          REFERENCE                TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
myapp         Deployment/myapp         8611m/10  1         10        4          74m
```
