### ISSUE TITLE
Crafted CN fields in CSRs can create confusing results in kubectl output

### ISSUE THREAD

**Issue by raesene** [kubernetes/kubectl#888]
**What happened**:

Data passed in the CN and O fields of a CSR submitted to the Kubernetes API server will be represented by kubectl in a way that could cause confusion for the administrator. It is possible to craft a CN field that modifies the appearance of the CSR when displayed with `kubectl describe`

As an example, the CSR below, has additional text in the CN field which when viewed with kubectl describe looks like this.

![output from kubectl describe](https://user-images.githubusercontent.com/68317/85948423-c4dfb300-b948-11ea-953f-cc9e4c162ebb.png)

From the screenshot there may be some confusion as to whether the O field in the certificate is "usergroup" , or "system:masters"

```yaml

apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: user2
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ29UQ0NBWWtDQVFBd1hERkJNRDhHQTFVRUF3dzRabTl2YkFvZ0lFOXlaMkZ1YVhwaGRHbHZiam9nZFhObGNtZHliM1Z3Q2dvZwpJRkpsY1hWbGMzUnZjaUJKYm1admNtMWhkR2x2YmpveEZ6QVZCZ05WQkFvTURuTjVjM1JsYlRwdFlYTjBaWEp6TUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNHFEbjh6aXNGYTh5TGpkaEErNm02K2pXaXF1Qi9wdTI5VTkzc3BtQURNTmkKbFhheTFtVnAwK0V6UVRRYWNaK0JRajhVdE9NdjJQL1FjV00vcDl5WHpIU0VRY2RUclhGL0pMTk03K1JLRzdmVXh0ZHB2Y3BTd09ycwpQbWVsSmJ4elVycmxWTm8vRUJvMzI1cHpZaDBGNHFiWUlZejhKSnNVcW1PUWdVTC9JcmdRcGJ2MjNBWWVFZVJDSUE2cUFTZEVReURKCmFKbGdFbndvMnZlcnRIcGRmVnNwbEJNKzZmMXd0cGJOaVEvVFF2eEUrZnk5U2hDVEtLbjM3OVVJRlFlQklhMVdBSEZXalU4UDlGemYKL2k2SDZEVk16YlB5d2pOVzlUOHgyMGV3bWtINlJOQllwcjUrb3h0Lytoc0RHTTBSU0R5TGtaS1lCK2REcUdIeDF2U0hYUUlEQVFBQgpvQUF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUs2UkFDb0pjYWFiZHowTWFaZ0lZa1JoeUhuYjlXdER6MVZvK3V2c0l4K2hYOUowCjcrTXNwTWUzZ1I3YUFhUzlNMmJjb2VRUDFkdGRlTFdPRzltMUZiMWl1RUZxZUx2ek1NMEJDNW9JRnZpa21FdW13d2NWZWdxdEZzNUkKTlpUK2hyQmN5Um51WHBrWVU2REdWbWFKK1pmSHE3dE13bDhZdUFxcEFNTUJ5cXdiY2tNWndObzhmL0xzVzFzYUFwN2laUjQ0VlpENwoxc29NaGdFWUdlazFsZGdodzE2MlVpTTNxNnlmdUpJcXl0YW5FeEVzaVdUdE80a1VBcmV2SjJKYjdZdHAyVEEwdmZVZXBWYmZwS3BWCis0YnNoRk9SNDRMTE9tYlhwekpVN3A5RUkyREErbm9RY2xhWkVGNW8vL1hCa1dscGY2b2trKzA0bkFLcHhRS1ZBbjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
```

Using openssl it's possible to see the modified CN field more clearly

![output from openssl](https://user-images.githubusercontent.com/68317/85948474-01131380-b949-11ea-88fe-e44fbdf92f41.png)

**What you expected to happen**:

Kubectl should escape any characters in the CSR object before displaying them to the user, to avoid any confusion about the structure of the CSR.

**How to reproduce it (as minimally and precisely as possible)**:

Apply the CSR above to a Kubernetes cluster, then issue the command `kubectl describe csr user2`

**Environment**:

- Kubernetes 1.18.2

**Comment by liggitt** [comment]
quoting the fields with %q would be reasonable

**Comment by enj** [comment]
The code is [here](https://github.com/kubernetes/kubernetes/blob/1cbda2493d2744af0d0e52b008976af0fc1d3a5e/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L3450-L3505) in case anyone wants to take a look.

**Comment by vinu2003** [comment]
Hey @raesene i can take a look at this as part of my learning task.
/assign @vinu2003

**Comment by vinu2003** [comment]
Hey @raesene , Is it worth Changing the CommonName to CN and O for usergroup ?

**Comment by raesene** [comment]
Hi all, 

I was reading [this issue](https://github.com/kubernetes/kubernetes/issues/101695) about output confusion in kubectl and it seems kind of similar to this one, so I wanted to check if we think that raising a CVE for this one would make sense as they have a similar impact.

I've checked on an up to date Kubernetes cluster and the output confusion is still present. The CSR below is requesting access to "admingroup" but from `kubectl describe csr` it could appear to be `usergroup`
![image](https://user-images.githubusercontent.com/68317/192140512-8e84e8bc-7914-4e74-a527-8719a298c081.png)


```yaml
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user2
spec:
  signerName: kubernetes.io/kube-apiserver-client
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ25UQ0NBWVVDQVFBd1dERkJNRDhHQTFVRUF3dzRabTl2YkFvZ0lFOXlaMkZ1YVhwaGRHbHZiam9nZFhObGNtZHliM1Z3Q2dvZwpJRkpsY1hWbGMzUnZjaUJKYm1admNtMWhkR2x2YmpveEV6QVJCZ05WQkFvTUNtRmtiV2x1WjNKdmRYQXdnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGlvT2Z6T0t3VnJ6SXVOMkVEN3FicjZOYUtxNEgrbTdiMVQzZXltWUFNdzJLVmRyTFcKWlduVDRUTkJOQnB4bjRGQ1B4UzA0eS9ZLzlCeFl6K24zSmZNZElSQngxT3RjWDhrczB6djVFb2J0OVRHMTJtOXlsTEE2dXcrWjZVbAp2SE5TdXVWVTJqOFFHamZibW5OaUhRWGlwdGdoalB3a214U3FZNUNCUXY4aXVCQ2x1L2JjQmg0UjVFSWdEcW9CSjBSRElNbG9tV0FTCmZDamE5NnUwZWwxOVd5bVVFejdwL1hDMmxzMkpEOU5DL0VUNS9MMUtFSk1vcWZmdjFRZ1ZCNEVoclZZQWNWYU5Udy8wWE4vK0xvZm8KTlV6TnMvTENNMWIxUHpIYlI3Q2FRZnBFMEZpbXZuNmpHMy82R3dNWXpSRklQSXVSa3BnSDUwT29ZZkhXOUlkZEFnTUJBQUdnQURBTgpCZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFzZHhhOHNlSS9ZQ1J3VjhrNzdxRDlVRy9objhzUm14YzBvOGNBa051WEdCQ0RZdnVnUlRsCjc0MzlGUTQwc2llN0x6OFJLY1AraGw5N3FZZG13N2xtaWh1cC9VZlNxK21TYzRka3R3MStJN2N3NWxma2liTzZGU29OdnZTWjIzUisKVkV6djBGWlQvY1dPeTVLcldpZklwcEliOGVuQ2ZLWmJFSng1VTJ0UkNac2FBc21TVlZqMCswS2ZrY1BYOG5YYW10QmpTU3VQZTRIWQpHb0d5S3crOVdKWlA2KzU4RzgxazAwVHljTjBmbFdmVGI2ZTF2ejZseWJXRVhxbnE3WXBHRE1KWC9TREpqNEc5OEFoenlPWVdKSEt1ClZmdVJiUHo4ci9iME0zQWFpcHBqc0FuTGh6ajRTOXEyM1ROR3ViTVlkQ0U4Ymt0dXYwKzBpb2dld2t1aFBRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  usages:
  - client auth

```

The technique is as described at the top of the post, embedded `\n` characters are being rendered by kubectl in a way that can confuse users.
