### ISSUE TITLE
Add support for kubectl apply/create/delete/update -f <filename> to specify some resources in the file

### ISSUE THREAD

**Issue by raravena80** [kubernetes/kubectl#900]
**What would you like to be added**:

If I have a service in my YAML manifest file I'd like to do something like this:

```bash
kubectl apply -f my.yaml service <service-name>
```

Background:

https://stackoverflow.com/questions/63237839/kubectl-deploy-only-one-component-from-a-yaml

**Why is this needed**:

It seems to be a more efficient handy way to talk to the API server using a file rather than editing a file or creating multiple copies of the file. There is kustomize but that doesn't necessarily work for people with large YAML manifests and who just want to apply/create/delete/etc certain parts of YAML file

**Comment by brianpursley** [comment]
If you label your resources, you might be able to use `--selector` (or `-l`).

For example, if I have this file, `nginx.yaml`:
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx2
  name: nginx2
spec:
  containers:
  - image: nginx2
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```

I can do this to only create nginx2:
```
$ kubectl apply -f nginx.yaml -l run=nginx2
pod/nginx2 created
```
