### ISSUE TITLE
Age printer column is no more reported when adding additional ones

### ISSUE THREAD

**Issue by prometherion** [kubernetes/kubectl#903]
**What happened**:

I'm developing some Custom Resource Definitions (CRDs) and noticed the missing of the column `AGE` when getting the resources from the CLI.

```
# kubectl get tenants.capsule.clastix.io
NAME   NAMESPACE QUOTA   NAMESPACE COUNT
oil    3                 1
```

The reason is that I'm implementing some additional columns using the `.spec.additionalPrinterColumns` array provided by `CustomResourceDefinition` Kind (`apiextensions.k8s.io/v1beta1`).

```yaml
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.namespaceQuota
    description: The max amount of Namespaces can be created
    name: Namespace quota
    type: integer
  - JSONPath: .status.size
    description: The total amount of Namespaces in use
    name: Namespace count
    type: integer
```

When I remove these two additional columns, the `AGE` is printed back correctly.

```
# kubectl get tenants.capsule.clastix.io
NAME   AGE
oil    117m
```

I'm not sure if this is a problem from `kubectl` or rather the _API Server_ perspective.

**What you expected to happen**:

Although adding additional printer columns, I'm expecting to get AGE as usual.

**How to reproduce it (as minimally and precisely as possible)**:

Try to install the following [CRD](https://github.com/clastix/capsule/blob/master/config/crd/bases/capsule.clastix.io_tenants.yaml) and applying a [sample definition](https://github.com/clastix/capsule/blob/master/config/samples/capsule_v1alpha1_tenant.yaml).

Getting the `tenants.capsule.clastix.io` from `kubectl` will not report the `AGE`.

**Anything else we need to know?**:

Not relevant.

**Environment**:

- Kubernetes client and server versions (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: KinD (Kubernetes in Docker)
- OS (e.g: `cat /etc/os-release`): 

```
NAME=Fedora
VERSION="30 (Workstation Edition)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**Comment by brianpursley** [comment]
[It looks like Age is just added as a default if you haven't defined any additionalPrinterColumns](https://github.com/kubernetes/kubernetes/blob/168f8f54f01b3b283fdd7494c5e94b22da4b2f72/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/helpers.go#L44-L51). You should be able to add it yourself if you want to include it for your CRD.

What if you you do something like this?

```
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.namespaceQuota
    description: The max amount of Namespaces can be created
    name: Namespace quota
    type: integer
  - JSONPath: .status.size
    description: The total amount of Namespaces in use
    name: Namespace count
    type: integer
  - JSONPath: .metadata.creationTimestamp
    description: The age of this resource
    name: Age
    type: date
```
