### ISSUE TITLE
"act-as" in kubeconfig doesn't work

### ISSUE THREAD

**Issue by bingosummer** [kubernetes/kubectl#935]
**What happened**:

1. I add "act-as" into the kubeconfig, follwing https://github.com/kubernetes/client-go/blob/5ab99756f65dbf324e5adf9bd020a20a024bad85/tools/clientcmd/api/types.go#L126.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: foo
    server: https://test:443
  name: test
contexts:
- context:
    cluster: test
    user: test
  name: test-admin
current-context: test-admin
kind: Config
preferences: {}
users:
- name: test
  user:
    client-certificate-data: foo
    client-key-data: foo
    token: foo
    act-as: bar
```

2. The header "Impersonate-User" is missing when I run "kubectl get node -v=9".

**What you expected to happen**:

The header `"Impersonate-User: bar"` should be added when I run "kubectl get node -v=9".
```
curl -k -v -XGET  -H "Accept: application/json, */*" -H "Impersonate-User: bar" -H "User-Agent: kubectl/v1.18.6 (linux/amd64) kubernetes/dff82dc" -H "Authorization: Bearer foo" 'https://test:443/api?timeout=32s'
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I guess other properties about impersonation also don't work.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
