### ISSUE TITLE
Clarify use of REMOTE_PORT when port-forward TYPE is service

### ISSUE THREAD

**Issue by montmanu** [kubernetes/kubectl#947]
**What would you like to be added**:

Documentation that clarifies the contextual nature of the `REMOTE_PORT` argument to `port-forward` when `TYPE` is `service`.

**Why is this needed**:

It is unclear from the current documentation that when `TYPE` is `service`, `REMOTE_PORT` represents a reference to a _Service_ port and not to a `containerPort`, as is the case for all other `TYPE`s.

Using the example resources provided below, it is unclear that the following command would fail since `8443` is not included in the Service's ports even though it is exposed in the pod's selected by that service.

```sh
$ kubectl port-forward service/kuard 8443
error: Service kuard does not have a service port 8443
```

Similarly, it is not clear that the following command would resolve `LOCAL_PORT` to `443`, and not to `8443` as it would for all other types.

```sh
$ kubectl port-forward service/kuard https
Forwarding from 127.0.0.1:443 -> 8443
Forwarding from [::1]:443 -> 8443
``` 

<details>
    <summary>Example Resources</summary>

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: kuard-tls
data:
  # replace with valid contents
  ca.crt: LS0tL...==
  tls.crt: LS0tL...==
  tls.key: LS0tL...==
type: kubernetes.io/tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      volumes:
      - name: tls
        secret:
          secretName: kuard-tls
          items:
          - key: tls.key
            path: kuard.key
          - key: tls.crt
            path: kuard.crt
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        volumeMounts:
        - mountPath: /tls
          name: tls
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: kuard
  type: LoadBalancer
...
```
</details>

Side note: I suspect that most users are not even aware that `port-forward` supports references to named ports for `REMOTE_PORT`, since it doesn't appear to be documented outside of the source code... perhaps this would be a good opportunity to kill two birds with one stone?
