### ISSUE TITLE
Setting remote http kubectl config by KUBECONFIG

### ISSUE THREAD

**Issue by evilrussian** [kubernetes/kubectl#950]
Hello!

**What would you like to be added**: i want to have feature to define remote (by http) kubectl config by env KUBECONFIG

**Why is this needed**: Let's say we have kubectl config with access to many clusters by oidc. Cluster kubeapi connected to one SSO. And we have 100+ users of clusters.  And all users have one same kubectl config. 

Example config:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.0.0.1:6443
  name: dev
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.0.0.2:6443
  name: prod
contexts:
- context:
    cluster: dev
    namespace: staging
    user: sso
  name: dev
- context:
    cluster: prod
    namespace: production
    user: sso
  name: prod
current-context: prod
kind: Config
preferences: {}
users:
- name: sso
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://sso.mysite.com/auth/realms/kubernetes
      - --oidc-client-id=kubernetes
      - --grant-type=password
      command: kubectl
      env: null
```
If something changed in config, it is hard to update config for all users ( they must download and apply new config to their computer). We could keep this config in the git and define the http link to the config for all users  via KUBECONFIG and all users to have automatic updates of kubectl config
For example:
```
export KUBECONFIG='https://gitlab.mysite.com/infrastructure/kubeconfig/-/raw/latest/config.yaml'
```
