### ISSUE TITLE
wait should leverage observedGeneration

### ISSUE THREAD

**Issue by KnicKnic** [kubernetes/kubectl#962]
**What would you like to be added**:
I would like for `kubectl wait --for=condition` to wait until observedGeneration reaches at least the generation when kubectl started.

Objects like Deployments have a `status.observedGeneration` (https://godoc.org/k8s.io/api/apps/v1#DeploymentStatus)
In addition the `condition` object in apimachinery also has a `observedGeneration` variable attached to it. see https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#Condition

I think wait should do the following.
1. retrieve the generation on the `metadata.generation` (https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#ObjectMeta)
1. wait for condition variable to exist
1. lookup condition variable and determine if it has a `observedGeneration`
    1. if so wait for `observedGeneration` to be >= previous `metadata.generation`
    1. condition variable doesn't have `observedGeneration` field
         1. wait for `status.observedGeneration` to be >= previous `metadata.generation`
             1. if `status.observedGeneration` also doesn't exist, continue to next step
1. wait for condition variable to be the correct value

**Why is this needed**:
script does the following
1. kubectl to update a CRD
    1. This causes a condition to go from `True` -> `False` when the controller will update the status
1. kubectl to wait for CRD to return condition `True`

However if the controller that updates the status has yet to realize the change and reset it to false by the time step 2 runs, kubectl will return immediately as the condition reflects stale state.

**Comment by eddiezane** [comment]
/triage accepted
/priority backlog

@RealHarshThakur are you interested in this one as well?

**Comment by RealHarshThakur** [comment]
@eddiezane Interested ? Yes !! I am bit occupied at the moment though. If someone else can do it before I get to it, that would be great.

**Comment by brianpursley** [comment]
@KnicKnic Can you provide a more specific example of the use case where this is a problem?  Preferably with some specific kubectl commands to demonstrate the problem.

**Comment by KnicKnic** [comment]
> @KnicKnic Can you provide a more specific example of the use case where this is a problem? Preferably with some specific kubectl commands to demonstrate the problem.

## Generic problem
@brianpursley The current wait functionality does not work in any condition in which a CRD needs to reset a condition upon update of the spec.

# Specific Example
## Background
I will invent a trivial CRD, that takes a container image, and has a condition whether or not that image is running Healthy. 
```yaml
kind: container
metadata:
  generation: 1
  name: example
spec:
  image: gcr.io/google_containers/pause-amd64:3.0
status:
  conditions:
  - lastTransitionTime: "2020-12-24T12:36:36Z"
    message: ""
    observedGeneration: 1
    reason: none
    status: "True"
    type: Healthy
```

## User Actions
The goal for us is to 
1. update the image
    1.  by setting the spec.image to `gcr.io/google_containers/pause-amd64:3.2`.
1. wait for the "container" to be healthy.

```yaml
kind: container
metadata:
  name: example
spec:
  image: gcr.io/google_containers/pause-amd64:3.2
```
```bash
cat above_file.yaml | kubectl apply -
kubectl wait --for=condition=Healthy container example
```

## Immediate result (current kubectl undesired behavior)
Now if we put a watch on the container crd example, or query it fast enough we will get the following 
```yaml
kind: container
metadata:
  generation: 2
  name: example
spec:
  image: gcr.io/google_containers/pause-amd64:3.2
status:
  conditions:
  - lastTransitionTime: "2020-12-24T12:36:36Z"
    message: ""
    observedGeneration: 1
    reason: none
    status: "True"
    type: Healthy
```
This is because the controller has yet to process the new `spec.image` and reset the `status.conditions[0].status` to "False". If we issue a `kubectl wait --for=condition=Healthy container example` at this time, the wait will return immediately with exitcode 0. This is because the condition is Healthy. I do not want it to return with healthy immediately & exit code 0. I wish for it to wait till the condition goes healthy. And I want that healthy to be the healthy that corresponds to the spec that exists at the time of issuing the wait request.

## Eventual Result (what we need to teach "kubectl --wait" to wait for)
The controller will eventually reset the status

```yaml
kind: container
metadata:
  generation: 2
  name: example
spec:
  image: gcr.io/google_containers/pause-amd64:3.2
status:
  conditions:
  - lastTransitionTime: "2020-12-24T12:40:36Z"
    message: ""
    observedGeneration: 2
    reason: none
    status: "False"
    type: Healthy
```

## Final state ("kubectl --wait" should complete)
Then when the container goes healthy it will get updated.

```yaml
kind: container
metadata:
  generation: 2
  name: example
spec:
  image: gcr.io/google_containers/pause-amd64:3.2
status:
  conditions:
  - lastTransitionTime: "2020-12-24T12:40:46Z"
    message: ""
    observedGeneration: 2
    reason: none
    status: "True"
    type: Healthy
```

I wish for `kubectl wait --for=condition=Healthy container example` to return only after this last update, or to fail with an exit code timeout is exhausted.

## Other precedents
A very similar thing to what I am asking is done for `kubectl rollout`. To ensure that it waits for the controller-manager has properly processed the request of doing the rollout and reflects the status of the rollout that was issued, kubectl checks the observedGeneration. See https://github.com/kubernetes/kubernetes/blob/0dfa4419a05318ffcfb7a34a7e599bed87ce4a37/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/rollout_status.go#L75
