### ISSUE TITLE
Kubectl command can not overwrite the service or deployment which be changed by manual update. 

### ISSUE THREAD

**Issue by Darren-wh** [kubernetes/kubectl#975]
Kubectl command can not overwrite the service or deployment which be changed by manual update. (for examples like service port or containers port)
1.Preparing the deployment and service
2.use the kubectl command to deploy service.
3.using the "kubectl edit deployment deployment" or service to add new Containers configuration and save.
Then kubernetes will do a rolling update.
4.using the kubectl command with old deployment and service code (without new Containers port) to deploy service.
Then the kubernetes will do a rolling update. And you can check the service or deployment, you will find new Containers configuration is still there., it doesn't be to overwrite by the old version.
5. The service has been updated ,  but the new add port configuration still.

>

for examples:
old service:
```
apiVersion: v1
kind: Service
metadata:
  name: test01
  namespace: ryu-dev
spec:
  selector:
    app: test-api
  ports:
    - name: test-api
      port: 8080
      targetPort: 8080
      protocol: TCP
```

kubectl edit  service  (add new port)
```
apiVersion: v1
kind: Service
metadata:
  name: test01
  namespace: ryu-dev
spec:
  selector:
    app: test-api
  ports:
    - name: test-api
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: test02-api
      port: 9100
      targetPort: 9100
      protocol: TCP
```
Then use the old version to apply the service. The service has been updated,  but the new add port configuration still there.
