### ISSUE TITLE
pod always pull image even if imagePullPolicy: IfNotPresent

### ISSUE THREAD

**Issue by boot-vue** [kubernetes/kubectl#992]
kubelet version:

```
Kubernetes v1.20.0
```

kubectl version: 

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4+k3s1", GitCommit:"2532c10faad43e2b6e728fdcc01662dc13d37764", GitTreeState:"clean", BuildDate:"2020-11-18T22:11:18Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

docker images  has exist `rancher/rancher:v2.5.3`:

```
REPOSITORY        TAG       IMAGE ID       CREATED       SIZE
rancher/rancher   v2.5.3    b75c693afd6b   12 days ago   970MB

```

helm repo : `https://artifacthub.io/packages/helm/rancher-stable/rancher`

kubectl edit deploy  rancher -n xxxx:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # .....
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rancher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rancher
        release: rancher
    spec:
        image: rancher/rancher:v2.5.3
        imagePullPolicy: IfNotPresent

        name: rancher
        ports:
        - containerPort: 80
         

# ........
```

kubectl describe pod rancher-84474b8b54-twszq -n xxx:

```yaml
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  15m   default-scheduler  Successfully assigned cattle-system/rancher-84474b8b54-twszq to node2
  Normal  Pulling    15m   kubelet            Pulling image "rancher/rancher:v2.5.3"

```

it always  pull image ,  delete all pods and recreated, same perfomance
