### ISSUE TITLE
.spec.clusterIP needs to be explicitly empty, if .spec.type = ExternalName

### ISSUE THREAD

**Issue by tavor** [kubernetes/kubectl#998]
**What happened**: 
Ran `kubectl apply -f my-service-config.yml`. 

Contents of `my-service-config.yml`:

```yml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ExternalName
  selector:
    app: my-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  externalName: my-service
```

And got:
```shell
The Service "my-service" is invalid: spec.clusterIP: Forbidden: must be empty for ExternalName services
```

**What you expected to happen**:
Since I didn't define a `.spec.clusterIP`, I'd expect,  in the case of `.spec.type = ExternalName`, that `.spec.clusterIP` is treated as empty.

**How to reproduce it (as minimally and precisely as possible)**:
I don't have a complete deployment/service example, but my guess is that using this deployment config (replacing the image with something like nginx) could be used with the service config above to replicate the issue:

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
        - name: my-service
          image: my-service:1
          ports:
            - containerPort: 8080
```

**Anything else we need to know?**:
Explicitly declaring an empty `.spec.clusterIP`
```yml
...
spec:
  clusterIP:
...
```
works.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```shell
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
Mac Catalina 10.15.7
